### PR TITLE
Added project structure gotcha.

### PR DESCRIPTION
**Pull request by cmelchior**
A small annoyance :(

@emanuelez 
@realm/java

### CODE REVIEW

**Comment by dalinaum** [comment]
We just encountered `Invalid checksum for file 'core-android-0.94.4.tar.gz'`

**Comment by zaki50** [comment]
:+1:

**Comment by cmelchior** [comment]
retest this please

**Comment by kneth** [comment]
:+1:

**Comment by dalinaum** [comment]
:+1:

**Pull request merged**
