### PR TITLE
Reflect hash code of rxObservableFactory in RealmConfiguration.hashCode().

### LINKED ISSUE #2420: RealmConfiguration.hashCode() should take into account rxObservableFactory

### PR DESCRIPTION
**Pull request by zaki50**
This fixes #2420

please review this @realm/java

### CODE REVIEW

**Comment by beeender** [comment]
:+1: For this PR.

More questions of putting the `RxFactory` into the `RealmConfiguration`. Since the `RxFactory` has nothing to do with the independent Realm, it won't effect read or write or the data structure of the `RealmObject`, IMO it is more like a static configuration which user should just set once.

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
@beeender It sounds reasonable.

**Comment by zaki50** [comment]
retest this please

**Comment by cmelchior** [comment]
:+1:

**Pull request merged**
