### PR TITLE
RealmQuery, RealmResults distinct() pt1

### PR DESCRIPTION
**Pull request by stk1m1**
A new PR for #1568

### CODE REVIEW

**Comment by cmelchior** [comment]
Once squashed this looks good :+1:

**Comment by stk1m1** [comment]
@cmelchior I'll convert distinct tests in RealmQueryTests to JUnit4 style.

**Comment by stk1m1** [comment]
retest this please

**Comment by stk1m1** [comment]
retest this please

**Comment by cmelchior** [comment]
Yay :shipit:

**Pull request merged**
