### PR TITLE
Change to is_not_null for links

### PR DESCRIPTION
**Pull request by beeender**
Since it is supported by core now.

https://github.com/realm/realm-core/pull/1185

### CODE REVIEW

**Comment by zaki50** [comment]
@beeender only available `isNotNull()`, and not `isNull()` yet?

**Comment by beeender** [comment]
@zaki50 It is available before. Before this change, we are using `not().is_null()` for `isNotNull` query since there is no native support for it in core at that time. This change is just to adapt the new core interface.

**Comment by zaki50** [comment]
So you don't mean this issue fixes #1693

**Comment by beeender** [comment]
No, it doesn't. It doesn't change anything user can feel. Just to use the proper core interface.

**Comment by zaki50** [comment]
@beeender I understand. thanks

**Comment by zaki50** [comment]
:+1:

**Comment by cmelchior** [comment]
:+1:

**Pull request merged**
