### PR TITLE
Better error reporting for custom getters and setters

### PR DESCRIPTION
**Pull request by kboyarshinov**
As been found at #952

### CODE REVIEW

**Comment by kneth** [comment]
Thank you for your contribution!

Please read and comply to https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md

**Comment by kboyarshinov** [comment]
@kneth submitted CLA.

**Comment by kneth** [comment]
@kboyarshinov Thank you.

**Comment by cmelchior** [comment]
Looks good to be. Great with added unit test
:+1:

**Comment by emanuelez** [comment]
:+1: Thank you for the contribution!

**Pull request merged**
