### PR TITLE
Upgrading to Realm Core 1.3.0.

### PR DESCRIPTION
**Pull request by kneth**
* Upgrading to Realm Core 1.3.0 (readding pre 1.1.2 sorting)
* Reverting callback for sorting (performance is back)

@realm/java

### CODE REVIEW

**Comment by stk1m1** [comment]
👍

**Comment by dalinaum** [comment]
👍

**Comment by kneth** [comment]
CI:retest

**Comment by beeender** [comment]
:+1:

**Comment by cmelchior** [comment]
:+1

**Pull request merged**
