### PR TITLE
Update sync 2.0.0-rc11

### PR DESCRIPTION
**Pull request by beeender**
There are some breaking changes from sync/core in this release:

- Object ID column name has been renamed from __OID to !OID
  Instead of hardcoding it in java, we read it from sync if it is built
  with sync. Otherwise hardcode it in JNI.
- SortDescriptor and DistinctDescriptor are separated into two classes.
  Change the related JavaSortDescriptor to adapt this change.
- Since core started using cmake, the openssl objects are not a part of
  core release anymore. Instead, it will be released to s3
  independently.

**DON'T MERGE THIS before followings done!!!!**
- [x] https://github.com/realm/realm-object-store/pull/467 needs to be merged first
- [x] Update the Object Store submodule.
- [x] Update ROS version.

### CODE REVIEW

**Comment by beeender** [comment]
@kneth I thought there would be a breaking change for distinct, but it seems all tests are fine?

**Comment by beeender** [comment]
@emanuelez help to take a look at the cmake part.

**Comment by Zhuinden** [comment]
@beeender core had a fix/breaking change/whatever that allows `realm.where().findAll().distinct()` to use `distinct()` on the query results themselves instead of the full table.

**Comment by beeender** [comment]
Also, since the `SortDescriptor` and `DistinctDescriptor` are separated in core, it would be good to do the same in java layer. I will do that in another PR -- not that urgent, we loose the type safety checking when calling into JNI anyway.

**Comment by beeender** [comment]
> If that core change is merged, I think @Deprecated should be removed from RealmResults.distinct().

I would still like to remove `Results.distinct()` majorly because of it can be achieved easily by contaminating other APIs:
```
RealmQuery query = realm.where(someclass).equalTo(1, "field);
RealmResults results = query.findAll();
results.distinct();
query.distinct(); // same
```
plus the semantics on `RealmResults.distinct()` is so unclear, it is not doing distinct on the original results, instead, it will create a new one.

also, to support that, also need to have `RealmResults.sort()`, same story. But all those can be achieved by `RealmQuery.distinct()`.

**Comment by kneth** [comment]
@beeender The new `distinct` will not be available before https://github.com/realm/realm-object-store/pull/467 is merged.

**Comment by beeender** [comment]
@kneth This is actually using commits from https://github.com/realm/realm-object-store/pull/467

**Comment by Zhuinden** [comment]
@kneth https://github.com/realm/realm-object-store/pull/467 is merged 😄

**Pull request merged**
