### PR TITLE
Remove Realm.getTable() from public API

### LINKED ISSUE #2546: getTable() deprecation warnings in generated classes
First I asked the question on SO (http://stackoverflow.com/questions/36230083/deprecation-warnings-after-switching-to-realm-88-2), but it seems like noone else noticed the issue or it happens only in my case.

#### Goal

Successful build with no warnings.

#### Expected Results

No warnings on compile build step.

#### Actual Results

```
{path-to-my-project}\build\generated\source\apt\debug\io\realm\ChoiceRealmProxy.java
Warning:(153, 32) [deprecation] getTable(Class<? extends RealmObject>) in Realm has been deprecated
Warning:(228, 32) [deprecation] getTable(Class<? extends RealmObject>) in Realm has been deprecated
```
Warnings like the one above that appear per each generated RealmProxy class (except these without `@PrimaryKey`).

##### Source class

```java
public class Choice extends RealmObject {

    @PrimaryKey
    @PrimaryKeyFactory.AutoIncrement
    private int id;
    @Required
    private String name;

    public Choice() {
        id = PrimaryKeyFactory.getInstance().nextKey(Choice.class);
    }
    public Choice(String name) {
        this();
        this.name = name;
    }
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
}
```

##### Part of generated class

```java

@SuppressWarnings("cast")
    public static Choice createOrUpdateUsingJsonObject(Realm realm, JSONObject json, boolean update)
        throws JSONException {
        Choice obj = null;
        if (update) {
            Table table = realm.getTable(Choice.class); //First warning
            long pkColumnIndex = table.getPrimaryKey();
            if (!json.isNull("id")) {
                long rowIndex = table.findFirstLong(pkColumnIndex, json.getLong("id"));
                if (rowIndex != TableOrView.NO_MATCH) {
                    obj = new ChoiceRealmProxy(realm.schema.getColumnInfo(Choice.class));
                    ((RealmObject) obj).realm = realm;
                    ((RealmObject) obj).row = table.getUncheckedRow(rowIndex);
                }
            }
        }
        if (obj == null) {
            if (json.has("id")) {
                if (json.isNull("id")) {
                    obj = (ChoiceRealmProxy) realm.createObject(Choice.class, null);
                } else {
                    obj = (ChoiceRealmProxy) realm.createObject(Choice.class, json.getInt("id"));
                }
            } else {
                obj = (ChoiceRealmProxy) realm.createObject(Choice.class);
            }
        }
        if (json.has("id")) {
            if (json.isNull("id")) {
                throw new IllegalArgumentException("Trying to set non-nullable field id to null.");
            } else {
                ((ChoiceRealmProxyInterface) obj).realmSet$id((int) json.getInt("id"));
            }
        }
        if (json.has("name")) {
            if (json.isNull("name")) {
                ((ChoiceRealmProxyInterface) obj).realmSet$name(null);
            } else {
                ((ChoiceRealmProxyInterface) obj).realmSet$name((String) json.getString("name"));
            }
        }
        return obj;
    }

@SuppressWarnings("cast")
public static Choice copyOrUpdate(Realm realm, Choice object, boolean update, Map<RealmObject,RealmObjectProxy> cache) {
        if (((RealmObject) object).realm != null && ((RealmObject) object).realm.getPath().equals(realm.getPath())) {
            return object;
        }
        Choice realmObject = null;
        boolean canUpdate = update;
        if (canUpdate) {
            Table table = realm.getTable(Choice.class); //Second warning
            long pkColumnIndex = table.getPrimaryKey();
            long rowIndex = table.findFirstLong(pkColumnIndex, ((ChoiceRealmProxyInterface) object).realmGet$id());
            if (rowIndex != TableOrView.NO_MATCH) {
                realmObject = new ChoiceRealmProxy(realm.schema.getColumnInfo(Choice.class));
                ((RealmObject) realmObject).realm = realm;
                ((RealmObject) realmObject).row = table.getUncheckedRow(rowIndex);
                cache.put(object, (RealmObjectProxy) realmObject);
            } else {
                canUpdate = false;
            }
        }

        if (canUpdate) {
            return update(realm, realmObject, object, cache);
        } else {
            return copy(realm, object, update, cache);
        }
    }
```

Warning is also present when I do not use PrimaryKeyFactory.

#### Version of Realm and tooling
Realm version(s): 88.2 (and I guess that other new plugin versions too)

Android Studio version: 2.0 beta7/RC1

Which Android version and device: minSdk 16, targetApi 23

### PR DESCRIPTION
**Pull request by beeender**
Close #2546

### CODE REVIEW

**Comment by beeender** [comment]
retest this please

**Comment by cmelchior** [comment]
Hmm, that unit test failure puzzles me quite a bit, but this seems :+1:

**Comment by beeender** [comment]
retest this please

**Comment by stk1m1** [comment]
:+1:

**Pull request merged**
