### PR TITLE
Fixes loggers

### PR DESCRIPTION
**Pull request by PavelSynek**
Fixes inital log level for DebugAndroidLogger and ReleaseAndroidLogger.
Also fixes logging with multiple loggers.

### CODE REVIEW

**Comment by cmelchior** [comment]
Hi @PavelSynek 
Thank you for fixing this. Really embarrassing bugs :), but guess they have gone unnoticed since we are only logging at WARN with one logger currently.

I think you need to sign our CLA before we can commit this, but apart from that it looks good: https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md

Our CI is acting up which is why the PR failed, so I don't expect you to need to fix anything.

**Comment by PavelSynek** [comment]
done

**Comment by kneth** [comment]
:+1:

**Comment by cmelchior** [comment]
:+1:

**Pull request merged**
