### PR TITLE
improve generated javadoc

### PR DESCRIPTION
**Pull request by larsgrefer**
link against JavaSE, Android, and RxJava

see also: realm/realm-android-adapters#55

### CODE REVIEW

**Comment by stk1m1** [comment]
@LarsFrid 

Thanks for your contribution. It would be easier if you could upload generated javadocs somewhere to compare. Javadoc generation is a part of release cycle and the end results affects everyone so we'd like to take some caution. Great work btw 👍

**Comment by larsgrefer** [comment]
@stk1m1 Here you go: http://larsgrefer.de/realm-javadoc/

For direct comparsion:

---
Current: https://realm.io/docs/java/1.1.0/api/io/realm/Realm.html
New: http://larsgrefer.de/realm-javadoc/io/realm/Realm.html

The reference to `java.lang.Object` is clickable now and links directly to http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html?is-external=true

---
Current: https://realm.io/docs/java/1.1.0/api/io/realm/RealmConfiguration.Builder.html#constructor.summary
New: http://larsgrefer.de/realm-javadoc/io/realm/RealmConfiguration.Builder.html#constructor.summary

`android.content.Context` now links to http://developer.android.com/reference/android/content/Context.html?is-external=true

Note that all links to http://developer.android.com/reference/ only work in the `NO FRAMES` view

**Comment by beeender** [comment]
:+1: :clap: :tada:

**Comment by cmelchior** [comment]
Very nice 👍 💯

**Pull request merged**
