### PR TITLE
Rename changelog.txt to CHANGELOG.md

### PR DESCRIPTION
**Pull request by danielgomezrico**

### CODE REVIEW

**Comment by dalinaum** [comment]
I think it's a good idea. How about this idea @realm/java

**Comment by cmelchior** [comment]
Yup, same. Sounds like a good idea to me as well :+1:

**Comment by beeender** [comment]
shall we merge this when release 0.88.0? otherwise need to fix conflicts from 0.87.x

**Comment by emanuelez** [comment]
A pure rename is hardly ever resolving in a conflict. it should be resolved automatically

**Comment by kneth** [comment]
Shouldn't we reformat it using markdown? For example `##` for each version.

**Comment by dalinaum** [comment]
version 1: `##` for each version
screen shot 2016-01-28 at 12 04 24 pm

version 2: `###`
screen shot 2016-01-28 at 12 04 39 pm

:+1: for `##`

**Comment by kneth** [comment]
Yes, `##` looks fine to me!

**Comment by cmelchior** [comment]
I'm fine with `##` as well

**Comment by dalinaum** [comment]
@danielgomezrico Can you update your PR?

**Comment by danielgomezrico** [comment]
@dalinaum updated :+1:

**Comment by dalinaum** [comment]
@danielgomezrico Can you add `##` for each version?

**Comment by danielgomezrico** [comment]
@dalinaum booom

**Comment by cmelchior** [comment]
Looks good to me :+1:

**Comment by kneth** [comment]
:+1:

**Comment by dalinaum** [comment]
@danielgomezrico Looks good to me too :) :+1: 
Did you sign our CLA before? Otherwise, you should sign our CLA.
https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#cla

**Comment by danielgomezrico** [comment]
@dalinaum just need to fill the google form right? (done)

**Comment by dalinaum** [comment]
Thanks for the contribution @danielgomezrico I will merge this PR.

**Comment by danielgomezrico** [comment]
:+1:

**Pull request merged**
