### PR TITLE
Remove unused defs of build.gradle.

### PR DESCRIPTION
**Pull request by dalinaum**
Please review this @realm/java

### CODE REVIEW

**Comment by cmelchior** [comment]
Seems you are right. At least I couldn't find anything referencing it :+1: 
You probably want to get @emanuelez nod of approval before merging though :)

**Comment by emanuelez** [comment]
Yes those are obsolete now :+1: You should probably address the release branch instead of master

**Comment by dalinaum** [comment]
Should I close this PR and make a PR for release branch?

**Comment by cmelchior** [comment]
:+1:

**Comment by beeender** [comment]
no no , this should go master

**Comment by kneth** [comment]
:+1:

**Pull request merged**
