### PR TITLE
Cleanup native methods in TableQuery

### PR DESCRIPTION
**Pull request by cmelchior**
Preparing to add `isEmpty()`
This reorders the native methods + fix their visibility pr. previous style fixes in other classes.

@realm/java

### CODE REVIEW

**Comment by kneth** [comment]
:+1:

**Comment by beeender** [comment]
:+1: But i am not sure if @nhachicha is happy of merging this one before his async :P

**Comment by emanuelez** [comment]
Of course he is :) :+1:

**Comment by nhachicha** [comment]
:+1:

**Pull request merged**
