### PR TITLE
Added missing changelog update.

### PR DESCRIPTION
**Pull request by cmelchior**
Missing change log update for #2240 

@realm/java
/cc @grahamsmith

### CODE REVIEW

**Comment by zaki50** [comment]
I think "Observable from findFirstAsync() not completing" is better than "findFirstAsync() not completing".

And shouldn't we mention the change of the behavior of `RealmChangeListener`?

**Comment by grahamsmith** [comment]
That does explain the issue better on my opinion.

Any chance of a mention for finding the issue? Trying to build open source
presence.

**Comment by stk1m1** [comment]
> I think "Observable from findFirstAsync() not completing" is better than "findFirstAsync() not completing".
:+1:

**Comment by cmelchior** [comment]
Actually the underlying error is that our changelistener wasn't triggered correctly, but since people are most likely to notice this using the Observable I am fine with changing it.

**Comment by cmelchior** [comment]
Updated @zaki50 @stk1m1 
Also added credit for @grahamsmith

**Comment by stk1m1** [comment]
:+1:

**Comment by kneth** [comment]
:+1:

**Pull request merged**
