### PR TITLE
[WIP] Update the build system to support encryption with new gradle tasks

### PR DESCRIPTION
**Pull request by emanuelez**
Compared to the previous solution this will allow to build both version without having to modify the `local.properties` file

### CODE REVIEW

**Comment by cmelchior** [comment]
Nice :+1:

**Comment by emanuelez** [comment]
In this case it's the same version, but different package name.
Using `crypto` in the version might mess up with people's dependencies if they don't specify a version

**Comment by emanuelez** [comment]
Ready for review. @kneth @bmunkholm @cmelchior 

My only doubt here is the behavior of the bintray section in the build file of the realm project. It allows me to specify multiple publications, but the pkg section does not reflect that. Will have to pay attention to what happens during the next release.

**Comment by emanuelez** [comment]
Made obsolete

**Pull request closed without merging**
