### PR TITLE
Expose bug when querying an indexed field with Case.INSENSITIVE

### PR DESCRIPTION
**Pull request by cmelchior**
Exposes #4788 
Waiting for https://github.com/realm/realm-core/pull/2675 to be fixed

### CODE REVIEW

**Comment by Zhuinden** [comment]
It is merged in core

**Comment by Zhuinden** [comment]
Realm Core 2.8.6 is released where this is pretty much the only update.

**Comment by Zhuinden** [comment]
If this is merged against the latest vers then this should pass?

**Comment by beeender** [comment]
@Zhuinden thanks! this change has been merged with another PR already.

**Pull request closed without merging**
