### PR TITLE
Make 1.0.0 header the same level as others

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Because this broke [realm-java's release notes](https://allmychanges.com/p/java/realm-java/#1.0.0) parsing at AllMyChanges.

### CODE REVIEW

**Comment by cmelchior** [comment]
Ups, thanks for catching that 👍

**Comment by emanuelez** [comment]
👍 :shipit:

**Comment by emanuelez** [comment]
@svetlyak40wt I know this is extremely silly for such a trivial change in a changelog file, but can you please accept our CLA? https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#cla

**Comment by kneth** [comment]
:+1:

**Comment by svetlyak40wt** [comment]
Accepted CLA.

**Comment by cmelchior** [comment]
@svetlyak40wt Thanks, merged.

**Pull request merged**
