### PR TITLE
Add support for RealmProxy#toString() to print length information for binary field

### LINKED ISSUE #1650: RealmProxy#toString() should print length information for binary field
Current implementation simply call `byte[].toString()` and `RealmProxy.toString()` generates something like `"Foo = [{foo:[I@23fc4bec}]"`.

We should print for `binary(25)`, `25 bytes binary`, etc.

### PR DESCRIPTION
**Pull request by joxon**
Fixes #1650

### CODE REVIEW

**Comment by cmelchior** [comment]
Hi @joxon Thank you very much for adding this 👏 . The change itself looks like, but it would be nice with a unit test as well to ensure that the functionality both works now and doesn't break in the future.

Also, it looks you already signed our CLA 👍

**Comment by bmunkholm** [comment]
An update in the changelog.md would also be needed.

**Comment by joxon** [comment]
> The change itself looks fine, but it would be nice with a unit test as well to ensure that the functionality both works now and doesn't break in the future.

Hi. I noticed there is an existing test case that could verify the correctness, Can I update that instead of writing new test case?

**Comment by bmunkholm** [comment]
@joxon Absolutely! That would be perfect!

**Comment by joxon** [comment]
Okay, the test cases are done. How should I update the changelog.md?

**Comment by cmelchior** [comment]
@joxon Thanks for doing this. I'll update the CHANGELOG you don't have to worry about it.

**Comment by Raynor999** [comment]
NPE： 
```
 field is ByteArray -> {
                            emitStatement("stringBuilder.append(\"binary(\" + field.length + \")\")")
                        }
```
https://github.com/realm/realm-java/pull/6767

Caused by: java.lang.NullPointerException: Attempt to get length of null array

**Pull request merged**
