### PR TITLE
optimize imports to reduce warnings

### PR DESCRIPTION
**Pull request by zaki50**
@realm/java

### CODE REVIEW

**Comment by kneth** [comment]
:+1:

Is there any way that we can automate this optimizations?

**Comment by dalinaum** [comment]
:+1:

**Comment by cmelchior** [comment]
:+1:

**Comment by zaki50** [comment]
@kneth AS has that feature.

**Comment by kneth** [comment]
@zaki50 Great! Thanks for find it for me.

**Pull request merged**
