### PR TITLE
Add support for in-memory Realm - squashed

### PR DESCRIPTION
**Pull request by beeender**
This is squashed commits of #1228 to make a better looking of git history.

I do guarantee this would be exact the same with SHA: 4d8e9df which is the last merge commit of #1228 .

### CODE REVIEW

**Comment by beeender** [comment]
@realm/java This would be the last time I bother you tonight.

**Comment by cmelchior** [comment]
I would just have squashed your original branch and force pushed it, but never mind :)
:+1:

**Comment by kneth** [comment]
:+1:

**Comment by emanuelez** [comment]
Yeah... just squash and force push next time :) :+1:

**Comment by beeender** [comment]
But that would loose all of the inline comments... I want gerrit!

**Comment by emanuelez** [comment]
I want Gerrit too! Let's be friends! :)

**Pull request merged**
