### PR TITLE
let clean task clean jni files

### PR DESCRIPTION
**Pull request by zaki50**

### CODE REVIEW

**Comment by zaki50** [comment]
Why checks failed...

**Comment by cmelchior** [comment]
```
io.realm.RealmTest > testQueriesFailWithInvalidDataTypes[Nexus 9 - 5.0.1] [31mFAILED [0m
	java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file.
	at io.realm.Realm.deleteRealm(Realm.java:1535)
```

Which is kinda odd since your PR had nothing to do with that.

**Comment by emanuelez** [comment]
retest this please

**Comment by kneth** [comment]
Should a clean remove the downloaded too?

**Comment by zaki50** [comment]
@kneth I think it's too heavy to re-download 200MB realm-core after every clean.
I propose to keep archive and to clean only extracted files when clean task executed.
And to ensure downloaded archive is not corrupted, I also propose to check
the hash of archive.
That check also guarantees the integrity of download file(not altered by some attackers).

```
diff --git a/realm-jni/build.gradle b/realm-jni/build.gradle
index 11204a0..d213d1b 100644
--- a/realm-jni/build.gradle
+++ b/realm-jni/build.gradle
@@ -1,4 +1,7 @@
+import java.security.MessageDigest
+
 ext.coreVersion = '0.93.0'
+ext.coreSha256Hash = '90044150ff6019a31c044306becccc513c7394f7486ffc8ba4880121c1ef46fa'
 ext.clang = false // gcc is default for the NDK. It also produces smaller binaries
 
 def commonCflags = [ '-std=c++11', '-ffunction-sections', '-fdata-sections', '-flto' ]
@@ -59,14 +62,14 @@ def targets = [
 
 buildscript {
     repositories {
-        mavenCentral()
+        jcenter()
     }
     dependencies {
-        classpath 'de.undercouch:gradle-download-task:1.0'
+        classpath 'de.undercouch:gradle-download-task:2.0.0'
     }
 }
 
-apply plugin: 'download-task'
+apply plugin: 'de.undercouch.download'
 
 Properties localProperties = new Properties()
 localProperties.load(new FileInputStream("${projectDir}/../local.properties"))
@@ -89,18 +92,48 @@ task checkProperties(group: 'check', description: 'Check the user provided gradl
     }
 }
 
-// TODO: Split this task into smaller subtasks
+ext.archiveFile = project.file("../core-android-${project.coreVersion}.tar.gz")
+ext.coreDir = new File(buildDir, "core-${project.coreVersion}")
+
 task downloadCore(group: 'build setup', description: 'Download the latest version of realm core', dependsOn: checkProperties) {
-    outputs.dir "../core-${project.coreVersion}"
+    outputs.upToDateWhen {
+        if (!project.archiveFile.exists()) {
+            return false
+        }
+
+        MessageDigest sha = MessageDigest.getInstance("SHA-256");
+        Formatter hexHash = new Formatter()
+        sha.digest(project.archiveFile.bytes).each { b -> hexHash.format('%02x', b) }
+        return project.coreSha256Hash.equals(hexHash.toString())
+    }
+
     doLast {
         download {
             src "http://static.realm.io/downloads/core/realm-core-android-${project.coreVersion}.tar.gz"
-            dest new File(buildDir, "core-android-${project.coreVersion}.tar.gz")
+            dest project.archiveFile
             onlyIfNewer true
         }
+    }
+}
+
+task verifyCore(type: de.undercouch.gradle.tasks.download.Verify, dependsOn: downloadCore) {
+    src       project.archiveFile
+    algorithm 'SHA-256'
+    checksum  project.coreSha256Hash
+}
+
+task deployCore(group: 'build setup', description: 'Deploy the latest version of realm core', dependsOn: verifyCore) {
+    doLast {
+        exec {
+            commandLine = [
+                    'rm',
+                    '-rf',
+                    project.coreDir.getAbsolutePath()
+            ]
+        }
         copy {
-            from tarTree(new File(buildDir, "core-android-${project.coreVersion}.tar.gz"))
-            into "../core-${project.coreVersion}"
+            from tarTree(project.archiveFile)
+            into project.coreDir
         }
         for (target in targets) {
             exec {
@@ -113,13 +146,6 @@ task downloadCore(group: 'build setup', description: 'Download the latest versio
                 ]
             }
         }
-        exec {
-            commandLine = [
-                    'rm',
-                    '-rf',
-                    "${projectDir}/build/*"
-            ]
-        }
     }
 }
 
@@ -143,7 +169,7 @@ targets.each { target ->
     task "buildAndroidJni${target.name.capitalize()}"(type: Exec) {
         group 'build'
         description "Build the Android JNI shared library for the ${target.name.capitalize()} platform"
-        dependsOn downloadCore
+        dependsOn deployCore
         dependsOn "generateNdkToolchain${target.toolchain.name.capitalize()}"
         environment PATH: "${buildDir}/standalone-toolchains/${target.toolchain.name}/bin:${System.env.PATH}"
         environment CC: "${target.toolchain.commandPrefix}-${clang?'clang':'gcc'}"
@@ -153,10 +179,10 @@ targets.each { target ->
             'make',
             '-C', "${projectDir}/src",
             "CC_IS=${clang?'clang':'gcc'}",
-            "REALM_CFLAGS=-Wno-variadic-macros -DREALM_HAVE_CONFIG -DPIC -I${projectDir}/../core-${project.coreVersion}/include",
+            "REALM_CFLAGS=-Wno-variadic-macros -DREALM_HAVE_CONFIG -DPIC -I${project.coreDir}/include",
             "CFLAGS_ARCH=${(commonCflags + target.cflags).join(' ')}",
             "BASE_DENOM=${target.name}",
-            "REALM_LDFLAGS=-lrealm-android-${target.name} -lstdc++ -lsupc++ -llog -L${projectDir}/../core-${project.coreVersion} -Wl,--gc-sections -flto",
+            "REALM_LDFLAGS=-lrealm-android-${target.name} -lstdc++ -lsupc++ -llog -L${project.coreDir} -Wl,--gc-sections -flto",
             'LIB_SUFFIX_SHARED=.so',
             "librealm-jni-${target.name}.so"
         ]
```

If this change is acceptable, I will make separate PR.

**Comment by emanuelez** [comment]
That looks nice! I'm currently considering moving to the official JNI support in the experimental plugin, but we will need to download core anyway so this is a very welcome change

**Comment by emanuelez** [comment]
I think this PR is ready for merge :+1:

**Comment by cmelchior** [comment]
We should have done this a long time ago. Thanks a lot :+1:

**Pull request merged**
