### PR TITLE
Use qualified name for model classes in generated code in order to avoid name conflict.

### PR DESCRIPTION
**Pull request by zaki50**
* [x] fix processor implementation
* [x] update processor tests
* [x] add tests that reproduce #3077
* [x] update changelog

This PR would conflicts with #2999 (bulk insert) and should be merged after the merge of #2999.

### CODE REVIEW

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
review this please @realm/java

**Comment by zaki50** [comment]
Ah,wait. I'll update this.

**Comment by zaki50** [comment]
done.
review this please @realm/java

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
retest this please

**Comment by cmelchior** [comment]
Nice. 👍

**Comment by beeender** [comment]
:+1:

**Comment by zaki50** [comment]
Thank you for reviwing.
I'll merge this after #2999's merge into `master`

**Pull request merged**
