### PR TITLE
Add an abstract RealmMigration class

### PR DESCRIPTION
**Pull request by wlxyhy**
User can extend this class to simplify realm migration

### CODE REVIEW

**Comment by cmelchior** [comment]
Can you give an example of how such a class could look like because I don't see what an abstract class could do better than an interface with a single method?

**Comment by Zhuinden** [comment]
It seems to be similar to what I tried to accomplish with [AutoMigration](https://github.com/Zhuinden/realm-auto-migration/blob/cbf0e73c2b1921ca59d179d8b05f1ea91218b3f3/auto-migration/src/main/java/com/zhuinden/realmautomigration/AutoMigration.java#L76).

In fact, I'm quite surprised that https://github.com/realm/realm-java/pull/6529/files#diff-7db08e5a4da97d5e99415e36d8b08743R96 works, that's pretty neat.

**Comment by wlxyhy** [comment]
> It seems to be similar to what I tried to accomplish with [AutoMigration](https://github.com/Zhuinden/realm-auto-migration/blob/cbf0e73c2b1921ca59d179d8b05f1ea91218b3f3/auto-migration/src/main/java/com/zhuinden/realmautomigration/AutoMigration.java#L76).
> 
> In fact, I'm quite surprised that https://github.com/realm/realm-java/pull/6529/files#diff-7db08e5a4da97d5e99415e36d8b08743R96 works, that's pretty neat. That would mean I can remove the `MigratedList` annotation I was hacking around with... 🤔

Yes, it's similar, I use abstract class just because
1. in some cases there's field to be renamed, so I add method renameFieldIfNeeded();
2.If you have more than 1 databases in your project, you can choose needed classes to add supported by getRealmClasses(). Can work with @RealmModule(classes = {x.class, xx.class})

**Comment by wlxyhy** [comment]
> Can you give an example of how such a class could look like because I don't see what an abstract class could do better than an interface with a single method?

In most cases, you don't have to add or remove fields when your realm needs migration, just update version of your realm is enough.

**Comment by cmelchior** [comment]
Hi @wlxyhy Thank you for this PR. 

While it probably does make sense to support some kind of auto-migration, I don't think adding this class is the right solution. The reason is that we actually already have support for this in [Object Store](https://github.com/realm/realm-object-store), it just hasn't been exposed in Java yet. And we wouldn't want to have this logic in multiple places.

You can see https://github.com/realm/realm-java/issues/2530 for more info.

**Pull request closed without merging**
