### PR TITLE
Bugfix binary isnotnull

### PR DESCRIPTION
**Pull request by kneth**
Reasoning about link queries is hard and a bug can easily be overlooked - even in tests.

Proposed entry in `changelog.txt`: Fixed bug in RealmQuery.isNotNull() for binary data.

@realm/java

### CODE REVIEW

**Comment by cmelchior** [comment]
If you update @beeender great diagram in `populateTestRealmForNullTests` with this:

```
        // Create 3 NullTypes objects. The objects are self-referenced (link) in
        // order to test link queries.
        //
        // +-+--------+------+---------+--------+--------------------+
        // | | string | link | numeric | binary | numeric (not null) |
        // +-+--------+------+---------+--------+--------------------+
        // |0| Fish   |    0 |       1 |    {0} |                  1 |
        // |1| null   | null |    null |   null |                  0 |
        // |2| Horse  |    1 |       3 |  {1,2} |                  3 |
        // +-+--------+------+---------+-----------------------------+
```
Then it looks good to me :+1:

**Comment by zaki50** [comment]
:+1:

**Comment by beeender** [comment]
@cmelchior The diagram actually made by @kneth :100:  All credits go to him!

**Comment by kneth** [comment]
@cmelchior I have updated the diagram.

**Comment by beeender** [comment]
:+1:

**Comment by cmelchior** [comment]
Looks great :+1:

**Pull request merged**
