### PR TITLE
Support unit tests with the plugin

### PR DESCRIPTION
**Pull request by droidpl**
This change will inject also the dependency for jUnit plain tests in Android

### CODE REVIEW

**Comment by cmelchior** [comment]
@droidpl I am not against adding this, but since you cannot run Realm on the JVM yet, you could not really use it, but perhaps you want to mock Realm in JVM tests?

👍 

Please review @realm/java

**Comment by zaki50** [comment]
And we need to apply our transformer to jvm tests

**Comment by cmelchior** [comment]
Ohh, good point. Forgot about that. That isn't supported by yet, right?

**Comment by droidpl** [comment]
As far as I know with robolectric there is some way to make it work instead of mocking everything, that is why I am proposing it. What do you think?

**Comment by cmelchior** [comment]
We have an issue here for tracking Robolectric support: https://github.com/realm/realm-java/issues/1867 , but as @zaki50 points out, right now the Transforms are not applied to JVM tests. Until that is fixed I don't think we should merge this PR. Sorry.

**Comment by droidpl** [comment]
Sure, just keep it there and lets wait it to be fixed. Thanks :)

**Comment by bmunkholm** [comment]
.

**Comment by cmelchior** [comment]
Outdated. Closing

**Pull request closed without merging**
