### PR TITLE
Test async transaction when async query existing

### PR DESCRIPTION
**Pull request by beeender**
To reproduce #1893

### CODE REVIEW

**Comment by dalinaum** [comment]
retest this please

**Comment by dalinaum** [comment]
retest this please

**Comment by beeender** [comment]
no need to retest this, this is just a failure test case without a fix :smile:

**Comment by dalinaum** [comment]
Oh. I see. Sorry. :)

**Comment by cmelchior** [comment]
Do we have another issue tracking this bug or... ?

**Comment by dalinaum** [comment]
@cmelchior I just started looking into #1893 again and I will use PR #2164 for this.

**Comment by cmelchior** [comment]
This has been incorporated into #2164, so closing now

**Pull request closed without merging**
