### PR TITLE
add SONAME header to shared libraries

### LINKED ISSUE #2432: Add DT_SONAME header to shared library
reported by takke in twitter https://twitter.com/takke/status/707922440068792322

Realm's shared libraries do not have DT_SONAME header in it.

current:
```
$ ./realm/realm-jni/build/standalone-toolchains/arm/bin/arm-linux-androideabi-objdump --private-headers  realm/realm-library/src/main/jniLibs/armeabi/librealm-jni.so |grep SONAME
```

### PR DESCRIPTION
**Pull request by zaki50**
Fixes #2432

Please review this @realm/java

### CODE REVIEW

**Comment by zaki50** [comment]
I thought that.
But, that version number is meaningless since `System.loadLibrary()` does not check `DT_SONAME` header.

**Comment by nhachicha** [comment]
:+1:

**Comment by emanuelez** [comment]
:+1:

**Comment by zaki50** [comment]
@cmelchior Is it OK to leave as it is? Or should we use `librealm-jni.so.0` as SONAME?

**Comment by cmelchior** [comment]
No it is fine as it is

**Pull request merged**
