### PR TITLE
Update proguard-rules.pro

### PR DESCRIPTION
**Pull request by skyisle**
Updated PR for #1904 @zaki50

### CODE REVIEW

**Comment by zaki50** [comment]
thanks @skyisle 

One more thing.
Please submit the CLA (see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#cla for details)

**Comment by zaki50** [comment]
:+1:

We need one more :+1: to merge, please review this @realm/java

**Comment by cmelchior** [comment]
:+1:

**Comment by zaki50** [comment]
@skyisle Sorry, you already submitted the CLA.

Great!

**Comment by skyisle** [comment]
Thanks :+1:

**Comment by zaki50** [comment]
I merged this into master as well.

**Comment by dalinaum** [comment]
Thanks @skyisle

**Pull request merged**
