### PR TITLE
Update Gradle to version 7.1.1

### PR DESCRIPTION
**Pull request by clementetb**
This PR upgrade Gradle to version 7.1.1+. 

During the upgrade we have encountered two issues:
- ErrorProne throws new errors, was disabled till they got addressed: #7551
- UnitTestExample tests don't pass because robolectric is not compatible with Gradle 7.1.1 #7550

### CODE REVIEW

**Comment by cmelchior** [comment]
It should be possible to upgrade to Gradle 7? As long as we stay on AGP 4.1 and CMake 3.18.*? At least that worked in Realm Kotlin

**Comment by clementetb** [comment]
@cmelchior Yes, it was possible.

I have repurposed this PR to upgrade to Gradle 7.1.1.

**Review by cmelchior — APPROVED** [review]
Nice 💯

**Comment by q464pp** [comment]
可以拉取合併嗎？謝謝

**Pull request merged**
