### PR TITLE
Update to Core v13.3.0

### PR DESCRIPTION
**Pull request by edualonso**
- Updated to Core v13.1.1.
- Fixed a bug that would result in `RealmDictionary` not being able to find `double` values due not taking the precision of the input parameter into consideration when using `RealmDictionary.contains`.
- Added a message buffer for our test logger since Core now logs more messages than before when logging. This broke our obfuscator tests.

### CODE REVIEW

**Comment by edualonso** [comment]
@cmelchior `clientReset_recoverOrDiscardUnsyncedChangesStrategy_fallback_userException_onAfterRecovery` fails similarly to the error I spotted in Kotlin and reported here https://github.com/realm/realm-core/issues/6070. Let's hold it until we hear more from Jonathan and Finn.

**Comment by clementetb** [comment]
Taking over this PR to bump to core 13.3.0

**Comment by BlueCobold** [comment]
Any news on this? Realm-Swift is using Core 13.x for a bit by now.

**Comment by BlueCobold** [comment]
Realm-Swift just updated core to 13.6.0. We're still waiting to become compatible again with Realm-Java. What's the problem here?

**Pull request closed without merging**
