### PR TITLE
Wrong url to gradle plugin

### LINKED ISSUE #1881: Small issue in Readme: Wrong url for SNAPSHOT releases
Ahoy! The URL for SNAPSHOT releases in the readme file is stale. It points to:

    classpath "io.realm:gradle-plugin:<version>-SNAPSHOT"

But the actual URL is:

    classpath "io.realm:realm-android:<version>-SNAPSHOT"

### LINKED ISSUE #1886: Realm 0.86.0 crashes when call clear()
I have updated Realm on my application from 0.85 to 0.86 and a crash occured at librealm_jni whenever I call clear. Below is my code which is working on 0.85.

```
        // remove the row if there is no downloaded document
        RealmResults<IngListDesc> lessonsToBeRemoved = expired.where()
                .equalTo("doc_downloaded", false)
                .findAll();

        // remove children
        mRealm.beginTransaction();
        for (int i=0; i < lessonsToBeRemoved.size(); i++) {
            RealmResults<IngDetailDesc> detailDescs =
                    lessonsToBeRemoved.get(i).getLessons().where().findAll();
            for (int j=0; j < detailDescs.size(); j++) {
                detailDescs.get(j).getObjects().where().findAll().clear();
            }
            detailDescs.clear();
        }
        lessonsToBeRemoved.clear();
        mRealm.commitTransaction();
```

### PR DESCRIPTION
**Pull request by kneth**
Fixes #1881  

Sorry for the mess.

@emanuelez

### CODE REVIEW

**Comment by cmelchior** [comment]
:+1:

Would it be worth mentioning we have two ways of deploying: FatJar and gradle plugin or do we leave that description for the website since SNAPSHOT by definition is bleeding edge and we want to transition away from the FarJar anyway?

**Comment by beeender** [comment]
:+1:

**Comment by kneth** [comment]
I think we should leave as it is. The `README.md` is for the ones who are looking for bleeding-edge or wish to build themselves.

**Comment by cmelchior** [comment]
Sounds fine with me

**Pull request merged**
