### PR TITLE
add Nullable annotation to methods that can return 'null'

### PR DESCRIPTION
**Pull request by zaki50**
This improves type inference in Kotlin.

### CODE REVIEW

**Comment by beeender** [comment]
Does this work with java 6?

**Comment by cmelchior** [comment]
It is purely used by lint tools, so I don't see any reason why it shouldn't?

**Comment by zaki50** [comment]
@cmelchior Kotlin seems to treat every *parameter* as nullable, but it infers every *return type* as non-null (at least AS uses non-null type when it generates a variable with explicit type for return value ).
If we add `ParametersAreNonnullByDefault` annotation, we at the same time need to add `Nullable` annotation to all nullable parameters. I'd like to give annotations to parameters in another PR.
Is it acceptable?

**Comment by Zhuinden** [comment]
I know my lib got a request to have @NonNull added to parameters consistently, especially on callback parameters (such as Realm realm; for executeTransactionAsync)

**Comment by zaki50** [comment]
I've changed target branch to `master`. And also added a changelog entry and fixed an error in kotlinExample.

**Pull request merged**
