### PR TITLE
Merge remote-tracking branch 'origin/releases' into mc/merge/0.88_a4d803d8

### LINKED ISSUE #2415: Gradle: Cannot find Relinker
Hi,
I am getting error when i try to use 0.88.0 instead of 0.87.5

`Error:Failed to resolve: com.github.KeepSafe:ReLinker:1.1`

### PR DESCRIPTION
**Pull request by beeender**
The problem is that libraries that use Realm were forced to tell users to add the jitpack repo manually, which is inconvenient.

Fixes #2415

### CODE REVIEW

**Comment by zaki50** [comment]
:+1:

**Comment by cmelchior** [comment]
Isn't this replaced by #2449 ?

**Comment by zaki50** [comment]
Seems yes. All changes are included in #2449.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:60783 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflgG-001eH9-2M
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:54:24 -0400
Date: Mon, 14 Mar 2016 09:14:06 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457972046;
	bh=6k04awTIxojO1e8HHIqavlkJ2rKO0GUxFjn7IB8juJ4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=fj+/qPXE457aEHuxTQuhbOTahFTo/oyJK/BO0L03AndIxSA/l/kIccFb5Ze+huESs
	 P6b+WLJMw4ZZs10bCkwPEUbhskBDJqXvwwd5/4E/Uqwk4QFwm18oCt/kIuxcy8fMLA
	 01DDFtVI+WQvL6exNP2czFmwMDXF7V1yzr68Hd7w=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:59026 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflk6-001g7a-Fb
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:58:22 -0400
Date: Mon, 14 Mar 2016 04:41:41 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457955701;
	bh=Yd1nWoHbE+GiPozVvx5+cSivqCiK71buWoUqBweqwGI=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=GaOcL8d4FgywPwPW2x6iB1vUCmR1jhw0N90fEt+LS6+L3HFgZbfI4F7prygNx7rNt
	 DwPjZLwJgTUwoEcc0pL2Oh9LXG3+h8BJilvEmq6rj96l+hhRO2l2hp3TP60lmp3Hez
	 slsLmp7lXRgrBOLCGdsdlvNZOvSgFRlGYe8aVEv4=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:43533 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmLp-001xDE-DW
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:37:21 -0400
Date: Mon, 14 Mar 2016 09:22:57 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457972577;
	bh=TzFh4Q6Nh6uTdUVxiuKOimk09S6T+HOPLxE5iHKj4p4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=mlc+Ur/5JQl+yVAz/UqREjStDFHhRfVcItdJ7AMDvdGy5vLRr/qAVcpP2+dSXT/Zt
	 qSaDf0kJhzVMECEBF62rFqa9a0MBiGqGcBRRQMAmggFXgI0VGgS89t9ymF4285u7vp
	 ogM4Eh4L2rtIWilCLpAV6Yv3M5YYBJqD+/CeUSsE=

**Pull request closed without merging**
