### PR TITLE
update kotlin version in example to 1.0.3

### PR DESCRIPTION
**Pull request by devholic**
[Kotlin 1.0.3](https://github.com/JetBrains/kotlin/blob/1.0.3/ChangeLog.md) is released, so I updated kotlin version in example 😄

### CODE REVIEW

**Comment by zaki50** [comment]
Thanks @devholic 

:+1:

**Comment by zaki50** [comment]
retest this please

**Comment by cmelchior** [comment]
👍

**Comment by zaki50** [comment]
@devholic Please merge `master` into `kotlin-1.0.3` branch in order to run CI.

**Comment by devholic** [comment]
@zaki50 I'm not familiar with git, so I added you to my repo. Sorry 😢

**Comment by zaki50** [comment]
@devholic Hmm, failed to push...

Could you check the permission?

```
$ git push -u devholic kotlin-1.0.3
ERROR: Permission to devholic/realm-java.git denied to zaki50.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
✘-128 ~/realm/realm-java [kotlin-1.0.3 ↑·3|⚑ 28]
```

**Comment by devholic** [comment]
@zaki50 I added you as a collaborator, but the invitation status is still pending :(
I think you can check invitation on https://github.com/devholic/realm-java/invitations

**Comment by zaki50** [comment]
@devholic Oh, it's my fault. I've accepted the invitation.

**Comment by zaki50** [comment]
I've rebased against master.

**Comment by devholic** [comment]
@zaki50 Thanks! 😄

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
@devholic Sorry for taking a long time. I've just merged your PR. Thanks!

**Comment by devholic** [comment]
Thanks 😄

**Pull request merged**
