### PR TITLE
Remove unnecessary modifiers

### PR DESCRIPTION
**Pull request by vbauer**

### CODE REVIEW

**Comment by cmelchior** [comment]
retest this please

**Comment by kneth** [comment]
@vbauer Please submit the CLA (see `CONTRIBUTING.md` for details)

Otherwise :+1:

**Comment by cmelchior** [comment]
retest this please

**Comment by vbauer** [comment]
I've just submitted CLA

**Comment by cmelchior** [comment]
Thanks for cleaning this up :+1:

**Comment by vbauer** [comment]
YW, thank you for merge. :)

**Pull request merged**
