### PR TITLE
update to Core 0.95.7

### PR DESCRIPTION
**Pull request by nhachicha**
Upgrade Core to 0.95.7 for 0.87.1 release

### CODE REVIEW

**Comment by nhachicha** [comment]
@realm/java

**Comment by emanuelez** [comment]
:+1:

**Comment by cmelchior** [comment]
:+1:

**Comment by beeender** [comment]
:+1:

**Comment by dalinaum** [comment]
:+1:

**Comment by zaki50** [comment]
:+1:

**Pull request merged**
