### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by erichkleung**
filed --> field

### CODE REVIEW

**Comment by nhachicha** [comment]
:+1:

**Comment by dalinaum** [comment]
retest this please

**Comment by zaki50** [comment]
Thanks for the PR, @erichkleung! We'll need you to accept our [Contributor License Agreement](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#cla) before we can merge your contributions.

**Comment by dalinaum** [comment]
Thanks @erichkleung 
LGTM :+1:

**Comment by erichkleung** [comment]
@zaki50 All good!

**Comment by dalinaum** [comment]
I'll merge this into master. Thanks for @erichkleung.

**Comment by zaki50** [comment]
Thanks @erichkleung!

**Comment by erichkleung** [comment]
You're very welcome; thanks for all the great work over at Realm!

**Pull request merged**
