### PR TITLE
update to sync 1.5.2

### PR DESCRIPTION
**Pull request by nhachicha**

### CODE REVIEW

**Comment by dalinaum** [comment]
Some headers such as `realm/group_shared.hpp` and `realm/util/meta.hpp` are excluded and there is a newly added header `realm/query_expression.hpp`. Where should I check to understand that?

**Comment by beeender** [comment]
Shouldn't this go to `releases` branch?

**Comment by nhachicha** [comment]
@dalinaum 
- For `realm/util/meta.hpp` see https://github.com/realm/realm-core/commit/5d4e626b7c8adb244d894cb654d107b1fc360c08

- `realm/group_shared.hpp` was unused (thanks AS)

- I added `realm/query_expression.hpp` in order to compile, otherwise you'll get
```
io_realm_internal_TableQuery.cpp:831:87: error: invalid use of incomplete type 'class realm::Columns<realm::StringData>'
                         ->and_query(table_ref->column<String>(size_t(arr[arr_len - 1]))
                                                                                       ^
In file included from /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/distribution/realm-core/core-1.5.2/include/realm/group.hpp:33:0,
                 from /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/distribution/realm-core/core-1.5.2/include/realm/group_shared.hpp:34,
                 from /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/distribution/realm-core/core-1.5.2/include/realm.hpp:22,
                 from /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp:19:
/Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/distribution/realm-core/core-1.5.2/include/realm/table.hpp:55:7: error: declaration of 'class realm::Columns<realm::StringData>'
 class Columns;
```

**Comment by nhachicha** [comment]
@beeender usually this goes to `master` example https://github.com/realm/realm-java/pull/4397 since it adds new feature. 
Also I need this for the Sync reconnect PR which is a new feature ==> `master`

**Comment by beeender** [comment]
#4397 contains a core breaking change (file format update). This one doesn't contain any user noticeable breaking changes I think? to `releases` will make our life for merging much easier ...

**Comment by nhachicha** [comment]
Opening against `releases`  https://github.com/realm/realm-java/pull/4486 cc @beeender

**Comment by dalinaum** [comment]
Thanks @nhachicha

**Pull request closed without merging**
