### PR TITLE
Update to Realm Sync beta.11

### PR DESCRIPTION
**Pull request by cmelchior**

### CODE REVIEW

**Review by rorbech — APPROVED** [review]
Are we not referencing Core fixes when we are still in beta?

**Comment by cmelchior** [comment]
All the Core fixes are for fileformat upgrades which aren't really relevant for the beta. All those fixes should be mentioned in the 7.x.x release notes though

**Comment by bmunkholm** [comment]
@cmelchior Are you 100% certain about that? Then the Core release notes should be updated as that's not clear?

**Comment by cmelchior** [comment]
Ah sorry. There is a rather big breaking file format change as well :(

**Comment by bmunkholm** [comment]
@cmelchior You are still missing to add the bugfixes from core release notes.

**Comment by bmunkholm** [comment]
We also need to be more specific about which Studio version is supported. Currently no version supports v20.

**Pull request merged**
