### PR TITLE
Parallelize make jobs

### PR DESCRIPTION
**Pull request by danielpovlsen**
@realm/java

### CODE REVIEW

**Comment by cmelchior** [comment]
Failing unit test is not related to this PR. It seems we have a unit test not behaving correctly elsewhere. 

This is "YES, PLEASE" :+1:

**Comment by emanuelez** [comment]
Hmmm `-j` will kill the load and IO. Supposing most of us (and the CI servers) have 4 cores I would suggest something like `-j8 -l4` so we enforce a limit based on the load.

**Comment by emanuelez** [comment]
retest this please

**Comment by danielpovlsen** [comment]
Optimally a cradle expert *wink, wink* will find a way to portably detect number of CPU cores. ;-)

**Comment by emanuelez** [comment]
I'm not aware of a way to do it in make (and that's why it's done in build.sh for core), but once we port our build system to pure Gradle it will be doable

**Comment by danielpovlsen** [comment]
These jobs are fairly small, so unless we are very strapped for memory I do not think it will be slower with just `-j` compared to `-j8`. And Infinitely™ faster compared with the current, implicit `-j1`.

**Comment by emanuelez** [comment]
Faster yes, but also making your machine hardly usable. At least that's my experience. @kspangsege Any experience on this?

**Comment by emanuelez** [comment]
Actually, since we instrument make from Gradle we can inject a `MAKE_FLAGS` variable and we can get the number of cores from the JVM with something like `Runtime.getRuntime().availableProcessors()`

**Comment by danielpovlsen** [comment]
w00t! :-D

**Comment by zaki50** [comment]
I tried 

            "-j${Runtime.getRuntime().availableProcessors() * 2}",
            "-l${Runtime.getRuntime().availableProcessors()}",

and it works good for me

**Comment by danielpovlsen** [comment]
@emanuelez Good to go?

**Comment by danielpovlsen** [comment]
@zaki50 Thanks!

**Comment by emanuelez** [comment]
Yes I agree with @zaki50 's suggestion

**Comment by danielpovlsen** [comment]
@emanuelez Well, actually, `availableProcessors()` already report logical cores, so I doubt that we would want to 2x that? Check out the last commit.

**Comment by emanuelez** [comment]
I know that. The 2x factor accounts for IO and it's pretty empirical but the `-l` assures we don't clog the CPU anyway

**Comment by nhachicha** [comment]
:+1:

**Comment by emanuelez** [comment]
:+1:

**Comment by dalinaum** [comment]
:+1:

**Comment by zaki50** [comment]
:+1:

**Pull request merged**
