### PR TITLE
Cast to int64_t when logging

### PR DESCRIPTION
**Pull request by beeender**
Otherwise is will be casted to bool when formatting.

### CODE REVIEW

**Comment by zaki50** [comment]
@beeender We should fix this comment as well.
 https://github.com/realm/realm-java/blob/v2.3.1/realm/realm-library/src/main/cpp/util.hpp#L79

**Comment by zaki50** [comment]
:+1:

**Comment by kneth** [comment]
Did we really only use `VOID_PTR` twice?

**Comment by beeender** [comment]
@kneth yeah!! removed them!

**Pull request merged**
