### PR TITLE
Fix the Eclipse folder in the distribution folder

### PR DESCRIPTION
**Pull request by emanuelez**

### CODE REVIEW

**Comment by emanuelez** [comment]
@cmelchior @kneth @bmunkholm

**Comment by kneth** [comment]
:+1:

**Comment by cmelchior** [comment]
Any reason for this change? It has been this way since the beginning and it doesn't point to any bug reports?

**Comment by emanuelez** [comment]
It's a mistake originated in the conversion of the script from bash to Gradle.

**Comment by cmelchior** [comment]
:+1:

**Pull request merged**
