### PR TITLE
Better handling of empty model classes in the code generator

### PR DESCRIPTION
**Pull request by emanuelez**

### CODE REVIEW

**Comment by emanuelez** [comment]
@bmunkholm @kneth @cmelchior

**Comment by cmelchior** [comment]
:+1: 
I assume this a fix for https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/realm-java/Vw5KeJ13UlM/slE-6GSLjroJ

**Comment by kneth** [comment]
:+1:

**Comment by bmunkholm** [comment]
update changelog!

**Comment by emanuelez** [comment]
Changelog entry proposal:
 * Improved handling of empty model classes in the annotation processor

**Comment by bmunkholm** [comment]
:+1:

**Pull request merged**
