### PR TITLE
Use createObject(class, primaryKey) in test

### PR DESCRIPTION
**Pull request by beeender**
Since Realm.createObject(class) will be deprecated on master for Classes
with primary key defined, fix the test cases which use it first to avoid
more conflicts when merging.

### CODE REVIEW

**Comment by zaki50** [comment]
There seems to be some other test cases that uses `createObject(Class)` for primary key classes.
All should be updated in this PR?

**Comment by cmelchior** [comment]
👍

**Comment by beeender** [comment]
@zaki50 Those in json need some other fixes as well... so i will fix them on master

**Comment by zaki50** [comment]
@beeender How about `RealmModelTests#createObject()` ?

**Pull request merged**
