### PR TITLE
Unit test cleanup and parameterization for PrimaryKey

### PR DESCRIPTION
**Pull request by stk1m1**
This PR is to address issue #2658 for adding more coverage and cleanup for PrimaryKey related unit tests.

**What is Done?**
1. With an exception, all the null primarykey tests in `RealmTests` are now parameterized.
2. Parameters in `RealmJsonNullPrimaryKeyTests` are cleaned up.
3. `Realm.createObject(class, primaryKeyValue)` is tested with `null` in positive and negative manner.
4. `NullPrimaryKey` interface is expanded to setters as well.

### CODE REVIEW

**Comment by cmelchior** [comment]
👍

**Comment by zaki50** [comment]
:+1:

**Comment by stk1m1** [comment]
@realm/java please review.

**Comment by kneth** [comment]
:+1:

**Comment by cmelchior** [comment]
👍

**Pull request merged**
