### PR TITLE
Convert test case to JUNIT4

### PR DESCRIPTION
**Pull request by beeender**
RealmAnnotationTest and RealmConfigurationTest.

### CODE REVIEW

**Comment by beeender** [comment]
retest this please

**Comment by cmelchior** [comment]
IMO we should just disable the failing unit test for now and await https://github.com/realm/realm-core/pull/1475

**Comment by cmelchior** [comment]
It looks like we are missing at least 1 test that actually uses a proper context now and not `getRoot()`, otherwise :+1:

**Comment by stk1m1** [comment]
:+1:

**Pull request merged**
