### PR TITLE
Added model/value-specific first()/last() to ManagedListOperator

### PR DESCRIPTION
**Pull request by Zhuinden**
Continued https://github.com/realm/realm-java/pull/5365 .

I believe it should be working this time!

### CODE REVIEW

**Comment by Zhuinden** [comment]
> This commit cannot be built

....

**Comment by zaki50** [comment]
The fail seems to be caused by our CI issue.

**Comment by Zhuinden** [comment]
Can you re-run this?

**Comment by zaki50** [comment]
@Zhuinden I couldn't find `rerun` button on CI. Could you push empty commit on the branch?

**Comment by cmelchior** [comment]
We had to disable running CI for external commits due to other security concerns. We need to download the PR and run manually :(

**Comment by Zhuinden** [comment]
Well, hopefully I didn't mess anything up this time, so if you find the time, then neat 😄 

But I actually needed `firstUncheckedRow` primarily for `RealmResults` which still has it, so this isn't critical for me right now. Basically an optimization for `RealmList.first()`/`RealmList.last()` if it is a model list. Assuming it works exactly as I expect.

**Comment by cmelchior** [comment]
@Zhuinden 

Not entirely sure whatis wrong, but cloning master from your fork indicate that:
```
   @Nullable
    @Override
    public final T first() {
        UncheckedRow row = collection.firstUncheckedRow();
        if (row == null) {
            return null;
        }
        //noinspection unchecked
        return (T) realm.get((Class<? extends RealmModel>) clazz, className, row);
    }

    @Nullable
    @Override
    public final T last() {
        UncheckedRow row = collection.lastUncheckedRow();
        if (row == null) {
            return null;
        }
        //noinspection unchecked
        return (T) realm.get((Class<? extends RealmModel>) clazz, className, row);
    }
```

`collection` is an unknown variable in `RealmList`?

**Comment by Zhuinden** [comment]
@cmelchior ......uerghh I couldn't get Android Studio to do even the most basics checks for me I guess 😭 

Technically it should be `getCollection()`.

**Comment by Zhuinden** [comment]
the managed list operator talks to an `osList` which is not `internal.Collection` so I think that explains why this isn't a thing.

Maybe some other time

**Pull request closed without merging**
