### PR TITLE
Classes are not properly transformed during androidTests

### PR DESCRIPTION
**Pull request by cmelchior**
Reproduces #2936 

Observations so far:
- All unit tests seems to work fine when run from inside the `realm-library` folder.
- Log says that all files should be transformed. 
- Decompiled .class files have not been transformed (which is also why the androidTest transformer crashes)
- Can only be reproduced if run from inside a proper app project (I modified unitTestExamples)

### CODE REVIEW

**Comment by emanuelez** [comment]
This seems to be a bug in Google's Transformer API. It looks like `TESTED_SCOPE` is not allowed as a scope but only as a referenced scope. https://github.com/JetBrains/adt-tools-base/blob/502506f2faf7acc13b5ebc909ea254fe32d02d33/build-system/gradle-core/src/main/groovy/com/android/build/gradle/internal/pipeline/TransformManager.java#L400

**Comment by cmelchior** [comment]
@emanuelez It looks intended to me though, so perhaps something we should create an issue for on `b.android.com`? I am not entirely sure why they would disallow transformers to run on test code though. Perhaps some other use case I am missing. 

So actions right now should the following, right?

1) Create bug on `b.android.com`
2) Document the quirks for `androidTest` code.

**Comment by chiuki** [comment]
Any news on this? I'm looking into using realm in my Android app and I have lots of tests and lots of direct field access. Thanks!

**Comment by cmelchior** [comment]
Hey @chiuku. Sorry  not yet. So far our best guess is that it is a bug in the Transform API. So for now it looks like direct field access cannot be used in instrumentation tests, unfortunately 😢

**Comment by chiuki** [comment]
That's unfortunate. I'll wait until that's fixed before looking into realm again.

Do you have the link to the bug on `b.android.com`? I'll watch that as well. Thanks!

**Comment by cmelchior** [comment]
Hey @chiuki 
Sorry for the late reply. This issue unfortunately got a bit lost in a vacation frenzy. I have created the issue here on b.android.com: https://code.google.com/p/android/issues/detail?id=219639&thanks=219639&ts=1470759569

**Comment by cmelchior** [comment]
I'll close this PR instead of keeping it open. It is still beeing referenced from https://github.com/realm/realm-java/issues/2936, so we can always dig it out if there is a change on Googles side

**Pull request closed without merging**
