### PR TITLE
Fixed RealmResults javadoc issues

### PR DESCRIPTION
**Pull request by ClaudiuBele**
@link tags have been corrected in RealmResults.java

### CODE REVIEW

**Comment by cmelchior** [comment]
Hi @ClaudiuBele 
Thank you for fixing this. We need you to fill out this before we can accept it though: https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md

Apart from that :+1:

**Comment by ClaudiuBele** [comment]
Submitted. Let me know if it went through.

**Comment by cmelchior** [comment]
It did, thanks.

**Comment by cmelchior** [comment]
@bmunkholm @emanuelez @kneth

**Comment by kneth** [comment]
:+1:

**Comment by emanuelez** [comment]
:+1: Thank you for the contribution @ClaudiuBele

**Pull request merged**
