### PR TITLE
Add test to open Realm database after compactRealm

### PR DESCRIPTION
**Pull request by zaki50**
test for #1581

I'm not sure that we should have this test in realm-java since it seems to be just testing the core.
What do you think @realm/java ?

### CODE REVIEW

**Comment by cmelchior** [comment]
Makes sense to me since :+1:

**Comment by dalinaum** [comment]
:+1:

**Comment by LiuDeng** [comment]
this still have problem！！！invalid realm format

**Comment by cmelchior** [comment]
@LiuDeng Please create a new issue with all relevant information if you are still having problems with this. If you can provide a sample project that shows it, it would be even better.

**Pull request merged**
