### PR TITLE
New migration + dynamic API

### PR DESCRIPTION
**Pull request by cmelchior**
Part of #880 

This PR adds the new migration and a dynamic API for working with Realm during migrations.

[ ] RealmSchema, for manipulating classes. Incl. test and JavaDoc.
[ ] RealmObjectSchema , for manipulating class fields.  Incl. test and JavaDoc. 
[ ] DynamicRealmObject.  Incl. test and JavaDoc.
[ ] DynamicRealmList.  Incl. test and JavaDoc.
[ ] Determine API for enumerating objects within RealmObjectSchema.

---

[ ] New Migrations example
[ ] Update docs

### CODE REVIEW

**Comment by zaki50** [comment]
How do I set schema version number after first installation in new migration API?
#886

**Comment by cmelchior** [comment]
@zaki50 This will be handled by #929 where it will be a method on the RealmConfiguration object.

**Comment by zaki50** [comment]
@cmelchior Great!

**Comment by cmelchior** [comment]
Superseded by #1200

**Pull request closed without merging**
