### PR TITLE
Update Gradle to version 2.4

### PR DESCRIPTION
**Pull request by emanuelez**
@cmelchior @kneth

### CODE REVIEW

**Comment by kneth** [comment]
@emanuelez did you measure the speedup for our builds?

**Comment by emanuelez** [comment]
I did on my local machine. The actual build is not improved by much, but the initial projects evaluation is waaayyyyy faster, especially in conjunction with the Gradle daemon (which is on by default when using Android Studio).

On a full no-op build it goes from 7 to 4 seconds

**Comment by kneth** [comment]
Sounds really good. Will a multicore build machine make it possible to enable parallel builds?

**Comment by emanuelez** [comment]
Parallel builds only affects native code, but we still use make for JNI so it does not affect us

**Comment by kneth** [comment]
:+1:

**Comment by cmelchior** [comment]
:+1:

**Pull request merged**
