### PR TITLE
Specified Realm.copyToRealm behaviour 

### LINKED ISSUE #1176: Docs not saying will method copyToRealm() deeply copy  object to Realm?
Docs not saying will method copyToRealm() deeply copy  object to Realm? By this I mean including other realm objects which are fields of copy object.

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #1176 

@kneth @emanuelez @nhachicha

### CODE REVIEW

**Comment by emanuelez** [comment]
:+1: :shipit:

**Comment by kneth** [comment]
What happens when you have a cyclic data structure? Should that case be documented?

**Comment by cmelchior** [comment]
It is copied as a cyclic datastructure. The recursive copy method keeps a reference to all copied data so we don't accidentally copy it twice. There is even a unit test for it ;)

Documenting it would not make much sense i think, as it would basically say "Also works with cyclic datastructures."

**Comment by kneth** [comment]
In that case :+1:

**Pull request merged**
