### PR TITLE
Make the native libraries way smaller.

### PR DESCRIPTION
**Pull request by emanuelez**
This is done reactivating link-time optimizations and using strip.

It is now also easier to switch between any supported version of gcc and clang

### CODE REVIEW

**Comment by emanuelez** [comment]
It required the latest NDK (r10d) to be installed on the Jenkins slave. It will also be needed to support ARM64.

Local final results:

CPU | Size
--- | ----
ARM | 809K
ARMv7a | 789K
MIPS | 1.6M
X86 | 1.3M


The jar file is now 1.9 MB

**Comment by cmelchior** [comment]
Totally awesome, but we also need to document the frontpage README with new NDK requirements.

**Comment by emanuelez** [comment]
Using gcc 4.8 the requirements did not change ☺

**Comment by emanuelez** [comment]
@cmelchior @kneth @bmunkholm @kspangsege

**Comment by kneth** [comment]
Nice job!

:+1:

**Pull request merged**
