### PR TITLE
Merge remote-tracking branch 'origin/release/0.87' into mc/merge/0.87_e5bd0080

### PR DESCRIPTION
**Pull request by beeender**
Conflicts:
	changelog.txt
	realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java

### CODE REVIEW

**Comment by beeender** [comment]
@nhachicha @realm/java

**Comment by dalinaum** [comment]
:+1:

**Comment by cmelchior** [comment]
:+1:

**Comment by nhachicha** [comment]
:+1:

**Pull request merged**
