### PR TITLE
Fix PMD error

### PR DESCRIPTION
**Pull request by dalinaum**
Please review this @realm/java

### CODE REVIEW

**Comment by dalinaum** [comment]
Ups. I only tested `./gradlew PMD`, it just encountered Findbugs' issues too.

**Comment by dalinaum** [comment]
retest this please

**Comment by dalinaum** [comment]
retest this please

**Comment by dalinaum** [comment]
```
[htmlpublisher] Archiving at BUILD level /home/jenkins/jenkins/workspace/java_pr/realm-library/build/reports/pmd to /var/lib/jenkins/jobs/java_pr/builds/3212/htmlreports/PMD_Issues
ERROR: Specified HTML directory '/home/jenkins/jenkins/workspace/java_pr/realm-library/build/reports/pmd' does not exist.
Build step 'Publish HTML reports' changed build result to FAILURE
```
It seems `/home/jenkins/jenkins/workspace/java_pr/realm-library/build/reports/pmd` was moved and it encountered the error. https://ci.realm.io/job/java_pr/3212/console

**Comment by beeender** [comment]
:+1:

**Comment by stk1m1** [comment]
:+1:

**Comment by beeender** [comment]
retest this please

**Comment by beeender** [comment]
retest this please

**Pull request merged**
