### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by bmunkholm**
Isn't the beta release versioned with a number?  "-beta.0"?
The date of the release needs update.

### CODE REVIEW

**Comment by bmunkholm** [comment]
Ok. So perhaps we should mention that in the release?
Also warn not to use this in production?
It makes it harder to handle bug reports, as we have no clue which version they saw the issue in :-)

**Comment by bmunkholm** [comment]
@cmelchior This also means we need to update the docs as we refer to "beta-0" there.

**Comment by nhachicha** [comment]
@bmunkholm fair point on the bug report, we can add `beta-0` as long as we suffix it with `-SNAPSHOT`, the warning could be added in the doc ...

**Comment by cmelchior** [comment]
Not sure it makes sense to add numbers to the beta label if we release as SNAPSHOT. 
I'll update the website docs to include the SNAPSHOT setup.

**Pull request merged**
