### PR TITLE
Always close shared group first before async msg

### PR DESCRIPTION
**Pull request by beeender**

### CODE REVIEW

**Comment by beeender** [comment]
@realm/java Quite difficult to make a test case of this ...

**Comment by beeender** [comment]
back to wip. My mind got corrupted today. This doesn't seem to be necessary.

**Comment by beeender** [comment]
Stupid me. This is not necessary.

**Comment by beeender** [comment]
Well, i found a good reason to merge this.

We support in-memory Realm which means if all of the Realm instances are closed, the next time, same name Realm opened should be a totally new Realm.

But if there is an shared group opened in other thread, core won't treat it as a brand new Realm. Instead, all of the old data will be there.

**Comment by beeender** [comment]
@realm/java

**Comment by nhachicha** [comment]
:+1:

**Comment by dalinaum** [comment]
:+1:

**Comment by kneth** [comment]
:+1:

**Pull request merged**
