### PR TITLE
Update android gradle to 2.1.0

### PR DESCRIPTION
**Pull request by beeender**

### CODE REVIEW

**Comment by nhachicha** [comment]
CI is failing, do we need to update the SDK Build Tool on CI?

**Comment by cmelchior** [comment]
We should probably also update all the examples as well, apart from that 👍

**Comment by beeender** [comment]
Do we really need sdk-manager-plugin? It seems Jake doesn't want to maintain it anymore.

See https://github.com/JakeWharton/sdk-manager-plugin/issues/99

**Comment by cmelchior** [comment]
I think people are moving over to this instead: https://github.com/tadfisher/android-sdk-updater

**Comment by beeender** [comment]
I guess we should remove the plugin and call https://github.com/tadfisher/android-sdk-updater in the CI script instead? @emanuelez

**Comment by cmelchior** [comment]
Bump @emanuelez

**Comment by beeender** [comment]
I will figure out. no need to bother @emanuelez .

**Comment by emanuelez** [comment]
`android-sdk-updater` won't work. This is what we need to do instead: https://github.com/JakeWharton/sdk-manager-plugin/issues/73#issuecomment-106747867

**Comment by cmelchior** [comment]
Still in review? Seems to be done now?

**Comment by jaredsburrows** [comment]
👍

**Comment by stk1m1** [comment]
👍

**Comment by cmelchior** [comment]
We should update examples as well to 2.1, but can be done in another PR. This is 👍

**Comment by dalinaum** [comment]
:+1:

**Comment by beeender** [comment]
@cmelchior Examples are updated https://github.com/realm/realm-java/pull/2743/files#diff-b234a7a9816dd9a9f74e749cb32d3efb

**Pull request merged**
