### PR TITLE
Test case fix

### PR DESCRIPTION
**Pull request by beeender**
@realm/java Strange, why didn't it crash on CI before?

### CODE REVIEW

**Comment by cmelchior** [comment]
retest this please

**Comment by cmelchior** [comment]
I am more worried, that it is actually possible to call `commit` twice in a row without the binding complaining about it. This PR is :+1:, but we should create an issue for it as it should throw an exception IMO.

**Comment by emanuelez** [comment]
:+1:

**Comment by beeender** [comment]
#1417 Created for tracking that issue. @cmelchior

**Comment by kneth** [comment]
One could argue that committing a read transaction is equivalent to do a refresh.

**Pull request merged**
