### PR TITLE
Static native method needs jclass

### PR DESCRIPTION
**Pull request by beeender**

### CODE REVIEW

**Comment by kneth** [comment]
Isn't the rule that you need `jclass` when you access a static field, and otherwise you use `jobject` (as `this`)?

**Comment by beeender** [comment]
Yes, rule is there. And also if the header file is generated from java class, this won't build because I added the warning checking.

But we always forget to update the header file when change native method declaration in java :(

We have to merge cmake!

**Comment by cmelchior** [comment]
Ups. I think that one is mine 👍

**Comment by kneth** [comment]
:+1:

**Pull request merged**
