### PR TITLE
Update core to 2.0.0-rc7

### PR DESCRIPTION
**Pull request by beeender**

### CODE REVIEW

**Comment by zaki50** [comment]
need to fix `inserts*` API?

**Comment by beeender** [comment]
@zaki50 I think i made them to call `addEmptyRowWithPrimaryKey()` last time, and did a check that they are using it. Or do i miss anything?

**Comment by kneth** [comment]
Looks good and can be merged when the native crash is resolved.

**Comment by zaki50** [comment]
@beeender seems OK...

**Pull request merged**
