### PR TITLE
change master version to 2.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by zaki50**

### CODE REVIEW

**Comment by zaki50** [comment]
fast-merge /cc @realm/java

**Comment by Zhuinden** [comment]
... Huh? Realm 2.1.0 already? I would have though that the immediate bug fixes would be a 2.0.1 version.

**Comment by zaki50** [comment]
`master` is a branch for the next minor release.
`releases` is the branch for bugfixes

**Comment by nhachicha** [comment]
@Zhuinden next release is `2.0.1` as
bug fixes goes to `release` & features to `master`

**Comment by spl** [comment]
See the [branch strategy](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#branch-strategy) by @beeender. 😄

**Comment by Zhuinden** [comment]
@spl oh, this is rather new! I see, sorry for the confusion :tongue:

**Pull request merged**
