### PR TITLE
addField PRIMARY_KEY should also apply REQUIRED

### LINKED ISSUE #2001: `addFiled` with `PRIMARY_KEY` doesn't apply `REQUIRED` modifier implicitly  (Original title - How to migrate a field's type the right way?)
Hey guys. I'm receiving an exception while trying to change a field's type.

Stacktrace: https://gist.github.com/Saketme/4b8f6274a0103165c79d
RealmObject: https://gist.github.com/Saketme/37894ccc5a1051cd8111
Migration: https://gist.github.com/Saketme/9ff0591dfdc45018e90b

In brief, I wanted to change a field's type from `long` to `String`. Retaining old values was not an option so the whole table had to be dropped. I however could not find a way to clear all items while migrating. Am I supposed to use `Realm.clear()` here?

### PR DESCRIPTION
**Pull request by beeender**
Fix #2001

### CODE REVIEW

**Comment by beeender** [comment]
@realm/java

**Comment by dalinaum** [comment]
It seems reasonable. :+1:

**Comment by cmelchior** [comment]
Ups, :+1:

**Comment by kneth** [comment]
:+1:

**Comment by beeender** [comment]
retest this please

**Comment by dalinaum** [comment]
retest this please

**Pull request merged**
