### PR TITLE
Fix a potential NPE

### PR DESCRIPTION
**Pull request by emanuelez**

### CODE REVIEW

**Comment by emanuelez** [comment]
@cmelchior @kneth @bmunkholm

**Comment by cmelchior** [comment]
Good catch, but if we are throwing an error on ```new RealmList(null)``` (which makes sense) should we not also do it on ```new RealmList(null, null)```? 

The later will get caught if you are trying to use ```Realm.copyToRealm()```, but not before?

**Comment by cmelchior** [comment]
Also, is worth a changelog entry?

**Comment by kneth** [comment]
:+1:

**Comment by bmunkholm** [comment]
: No additional comments.

**Pull request merged**
