### PR TITLE
Unit test to expose timeout in finalizer

### PR DESCRIPTION
**Pull request by kneth**
#1342 is reporting a timeout of the finalizer watchdog. When you have many objects in a Realm, and you iterate through them in multiple threads, many temporary objects are created. Disposal of these temporary objects might take too long (Android's limit is 10 seconds), and the exception as mentioned in #1342 is thrown.

Relevant background info: http://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin

### CODE REVIEW

**Comment by kneth** [comment]
We should probably find a data structure more efficient than `HashMap` but for now it is a good fix.

I have tested locally on Unnecto U511 (256 MB memory) and OnePlus One (3 GB memory) with success.

:+1:

**Comment by beeender** [comment]
:+1: :100:  And needs to disable the test before merge~

**Comment by meierjan** [comment]
In which version was this fixed?

**Comment by kneth** [comment]
The fix closing this issue goes back to version 0.89. We have gradually moved over to phantom references to get rid of similar issues.

**Comment by meierjan** [comment]
Okay, because I have an app using version 0.9 and I am getting this - but maybe it's coming from something else. Thanks anyways for the very fast response

**Comment by kneth** [comment]
@meierjan If you can, consider to upgrade to a recent version. As I said, we have fixed similar issues but in 0.89 we fixed the first major one.

**Comment by Zhuinden** [comment]
> 2.2.2 (2017-01-16)
>
> Use phantom reference to solve the finalize time out issue (#2496).

But if you support devices < API 16, then 3.1.2+ is the way to go... so 3.1.4 or 3.3.1.

**Comment by meierjan** [comment]
Thanks for the info guys. Rlly amazed by how helpful you are. Yeah maybe I have to take the time and update.

**Pull request merged**
