### PR TITLE
Allow the publishing on SNAPSHOT artifacts to oss.jfrog.org

### PR DESCRIPTION
**Pull request by emanuelez**
If the version doesn’t end with -SNAPSHOT the publishing will be a null
operation.

### CODE REVIEW

**Comment by emanuelez** [comment]
@cmelchior @kneth @bmunkholm

**Comment by cmelchior** [comment]
I am could use some documentation on how to upload SNAPSHOT vs. Release builds. Perhaps add some documentation to the top of the file?
```
./gradlew uploadArchives // Upload SNAPSHOT?
./gradlew bintrayUpload // Upload release
```

**Comment by emanuelez** [comment]
It's `./gradlew realm:publish` to publish snapshots, but it will be done automatically by Jenkins

**Comment by cmelchior** [comment]
Yes, but I thought the standard task for that kind of stuff was uploadArchives, guess i am wrong?
Anyway, that is why it is nice to have it documented for the day that Jenkins is broken and we need to do it by hand :)

**Comment by emanuelez** [comment]
`publish` is the standard task produced by the official `maven-publish` Gradle plugin.
I think this documentation would be better suited in a Wiki, and not in the public repo

**Comment by cmelchior** [comment]
Fair enough. Just put it somewhere ;)
:+1:

**Comment by kneth** [comment]
:+1:

**Pull request merged**
