### PR TITLE
Remove duplicated gradle wrapper.

### PR DESCRIPTION
**Pull request by dalinaum**
If we need this duplicated gradle wrapper, we can use `../gradlew` instead.

### CODE REVIEW

**Comment by dalinaum** [comment]
Please review this @realm/java

**Comment by emanuelez** [comment]
The realm folder is a standalone gradle project so it needs those files

**Comment by dalinaum** [comment]
I didn't delete gradle files of realm. They are all gradle wrapper. Is `../gradlew` enough to use realm folder? Is there corner cases? I don't think every gradle projects need its own gradle wrapper.

**Comment by zaki50** [comment]
We import the `realm` folder to Android Studio as a project root, and Android Studio should be able to find the gradle wrapper on the project root.

So we should keep files of gradle wrapper in the `realm` folder.

**Comment by dalinaum** [comment]
I see.I will close this.

**Pull request closed without merging**
