### PR TITLE
Add thread check to methods in DynamicRealmObject

### LINKED ISSUE #4258: Do thread checking in DynamicRealmObject
Methods in `DynamicRealmObject` don't have thread checks.

I wrote following test to expose this bug.
```
    private enum ThreadConfinedMethods {
        GET_LONG,
    }

    private static void callThreadConfinedMethod(DynamicRealmObject obj, ThreadConfinedMethods method) {
        switch (method) {
            case GET_LONG:
                obj.getLong(AllJavaTypes.FIELD_LONG);
                break;

            default:
                throw new AssertionError("missing case for " + method);
        }
    }

    @Test
    public void callThreadConfinedMethodsFromWrongThread() throws Throwable {

        dynamicRealm.beginTransaction();
        dynamicRealm.deleteAll();
        final DynamicRealmObject obj = dynamicRealm.createObject(AllJavaTypes.CLASS_NAME, 100L);
        dynamicRealm.commitTransaction();

        final AtomicReference<Throwable> throwableFromThread = new AtomicReference<Throwable>();
        final CountDownLatch testFinished = new CountDownLatch(1);

        final String expectedMessage;
        //noinspection TryWithIdenticalCatches
        try {
            final Field expectedMessageField = BaseRealm.class.getDeclaredField("INCORRECT_THREAD_MESSAGE");
            expectedMessageField.setAccessible(true);
            expectedMessage = (String) expectedMessageField.get(null);
        } catch (NoSuchFieldException e) {
            throw new AssertionError(e);
        } catch (IllegalAccessException e) {
            throw new AssertionError(e);
        }

        final Thread thread = new Thread("callThreadConfinedMethodsFromWrongThread") {
            @Override
            public void run() {
                try {
                    for (ThreadConfinedMethods method : ThreadConfinedMethods.values()) {
                        try {
                            callThreadConfinedMethod(obj, method);
                            fail("IllegalStateException must be thrown.");
                        } catch (Throwable e) {
                            if (e instanceof IllegalStateException && expectedMessage.equals(e.getMessage())) {
                                // expected exception
                                continue;
                            }
                            throwableFromThread.set(e);
                            return;
                        }
                    }
                } finally {
                    testFinished.countDown();
                }
            }
        };
        thread.start();

        TestHelper.awaitOrFail(testFinished);
        final Throwable throwable = throwableFromThread.get();
        if (throwable != null) {
            throw throwable;
        }
    }
```

### PR DESCRIPTION
**Pull request by zaki50**
fixes #4258

@realm/java

### CODE REVIEW

**Comment by nhachicha** [comment]
`add_set_dynamicObjectFromOtherThread` is failing

**Comment by zaki50** [comment]
@nhachicha I executed the tests locally with all changes stashed. So stupid...

The failure was fixed!

**Comment by zaki50** [comment]
@nhachicha Could you review this again?
I modified `RealmList.java` to fix the failure, and also modified `RealmListTests.java` to fix test process crash on test failure (test logic itself is the same).

**Comment by nhachicha** [comment]
@zaki50 LGTM If CI is happy

**Pull request merged**
