### PR TITLE
update realm logo

### PR DESCRIPTION
**Pull request by zaki50**
@realm/java

### CODE REVIEW

**Comment by beeender** [comment]
:+1:

**Comment by stk1m1** [comment]
👍

**Comment by kneth** [comment]
:+1:

**Comment by cmelchior** [comment]
👍

**Comment by jpsim** [comment]
how about `logo.png`, referenced in the `README.md`?

**Comment by zaki50** [comment]
@jpsim Good catch!

Updated

**Comment by cmelchior** [comment]
@zaki50 I think the one with Orby would be more accurate: https://drive.google.com/folderview?id=0BzeKUYqyvz3hNUdnTEdfNnNzYmc&tid=0B7NPNr8SRNBrSDhvRklHQktfV3c

**Comment by nhachicha** [comment]
👍

**Comment by dalinaum** [comment]
:+1:

**Comment by zaki50** [comment]
@realm/java update logo to reflect the comment of https://github.com/realm/realm-java/pull/2924#issuecomment-223744597

**Comment by cmelchior** [comment]
:shipit: 👍

**Pull request merged**
