### PR TITLE
update logo

### PR DESCRIPTION
**Pull request by nhachicha**
screen shot 2016-05-24 at 19 24 25
screen shot 2016-05-24 at 19 24 41

### CODE REVIEW

**Comment by nhachicha** [comment]
@realm/java

**Comment by emanuelez** [comment]
Using vectors would be nice, also for the size of the repo

**Comment by cmelchior** [comment]
Agree. It would also be crisper on all densities, but for now 👍

**Comment by emanuelez** [comment]
once the PNGs are in the repo we won't be able to get rid of them anymore, but oh well...

**Comment by kneth** [comment]
LGTM

**Comment by nhachicha** [comment]
@cmelchior I don't wont to rely on the Android downscale/upscale from `xxx-hdpi` I mean we're talking about `61 KB` for all resources here 😒

**Comment by cmelchior** [comment]
It it just the examples so  ¯\\\_(ツ)\_/¯
This is fine 👍

**Pull request merged**
