### PR TITLE
added thread check to Realm#createObject(Class,Object)

### PR DESCRIPTION
**Pull request by zaki50**
Thread check in `Realm#createObject(Class,Object)` seems to be missing.

@realm/java

### CODE REVIEW

**Comment by beeender** [comment]
add a test case? See `RealmTests.runMethodOnWrongThread()`

**Comment by zaki50** [comment]
@beeender nice. I've added it.

**Comment by cmelchior** [comment]
👍

**Comment by beeender** [comment]
:+1:

**Pull request merged**
