### PR TITLE
fix typo in RunInLooperThread.java

### PR DESCRIPTION
**Pull request by zaki50**
@realm/java

### CODE REVIEW

**Comment by zaki50** [comment]
retest this please

**Comment by cmelchior** [comment]
:+1:

**Comment by cmelchior** [comment]
Maybe we should disable the unit test again. It doesn't look as fixed as I original thought?

**Comment by stk1m1** [comment]
As soon as Mr. Jenkins says it's all good, :+1:

**Comment by zaki50** [comment]
Is it OK to merge this?

**Comment by cmelchior** [comment]
Yes, just merge it.

**Pull request merged**
