### PR TITLE
Support building SDK with JVM 11

### LINKED ISSUE #7179: Support JDK9
Currently compiling with JDK9 on macOS fails 

```
cd realm-transformer
/gradlew assemble
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0

```

```
java -version                                                                                                                
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

Specifying JDK8 explicitly alleviate the issue 
```
./gradlew assemble  -Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/
```

Document or support this behaviour

### LINKED ISSUE #7474: Support RealmObject referencing a RealmObject from a different compilation module
#### Describe your problem or use case
When modularising an app by feature, there may be a common structure that is used by many features, and a Realm representation of this structure may want to be shared by sitting in a common module.

For instance, we may have a profile feature, and an album feature, both of which want to save media information, so you would have:
- Profile Module (depends on core)
- Album Module (depends on core)
- Core module

And Profile Module has

```
open class RealmProfile(var media: RealmMedia? = null): RealmObject()
```

Album Module

```
open class RealmAlbum(var media: RealmMedia? = null): RealmObject()
```

Core Module

```
open class RealmMedia(var name: String? = null): RealmObject()
```

Right now, this will throw an exception in the annotation processor because RealmMedia cannot be found. This can be solved by marking the RealmMedia object as embedded, but there may be some situations where these two things may want to reference the same object.

#### Describe the solution you'd like
From my brief look at the issue in the processor, it needs to find the referenced class to see whether the class has a primary key to change insertion behaviour. It seems like it should be possible to add information to a RealmClass annotation to tell the processor this information (as the processor can determine whether the referenced class is embedded or not from the annotation), something like:

```
@RealmClass(hasPrimaryKey = RealmHasPrimaryKey.TRUE)
open class RealmMedia(var name: String? = null): RealmObject()
```

where the RealmHasPrimaryKey enum is like:
```
public enum RealmHasPrimaryKey {
    TRUE, FALSE, UNDEFINED
}
```

This way if the hasPrimaryKey field is set to either TRUE or FALSE the processor can use that field, and if it is undefined it can fall back to the default of looking up the class in the parsed collection.

#### Additional context
There is a git repo that hits the existing issue here: https://github.com/jd565/realm-modularised/tree/main

### LINKED ISSUE #7533: Upgrade to Java 11
With Android Studio Arctic Fox, the default Java version shipped is now Java 11.

In order to avoid too many project-specific environment requirements, we should attempt to support this version as a minimum.

Currently, we depend on Java 8 due to https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/build.gradle#L15.

This is required due to this extension function https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.kt#L649.

Unfortunately, it seems that these API's moved in Java 9 to the `jdk.compiler` module https://docs.oracle.com/javase/9/docs/api/com/sun/tools/javac/package-summary.html

I haven't tried to use Java 9 modules yet, so it is a bit unclear if we can actually use these and still be compatible with Java 8. 

Forcing consumers to be on Java 9 or 11 seems a rather big breaking change. An alternative could be to call into all of these API's using reflection. That might be acceptable since the code path is already expected to be "slow".

This upgrade is further made difficult by the fact that it doesn't seem we have any tests that actually exercise the code path :(

### PR DESCRIPTION
**Pull request by rorbech**
Closes #7533 
Closes #7179
Closes #7474 - Separated the actual fix of this into it's own PR in #7525

**TODO**
- [x] 1. @rorbech  merges https://github.com/realm/realm-java/pull/7525 to master and then back into https://github.com/realm/realm-java/pull/7535
- [x] 2. @clementetb  upgrades the project so it can compile with Java 11, i.e. fix Annotation Processor / CI.
This also include doing work on CI so we e.g. compile the introExample with both Java 8 and Java 11 to catch future regressions. #7539
  - [x] Use JDK 11 on CI
  - [x] Fix Javadoc generation
  - [x] Fix jni header generation. JDK 11 requires new CMake construct for generating the headers (https://cmake.org/cmake/help/latest/module/UseJava.html#header-generation)
  - [x] Include building at least one example project (introExample?) with both JDK 8 and JDK 11 on CI.
- [x] 3. XXX upgrades our own repo to Gradle 7.11 and AGP to 7.0.0 and fix resulting issues (there seems to be a few). We need to take special care that our Gradle Plugin / Transformer / Annotation Processor still work with pre-7 and post-7 Gradle/AGP #7548
- [x] 4. We fix whatever needs fixing in the Gradle Plugin so we work with the configuration cache: https://github.com/realm/realm-java/issues/7299 in #7535
- [x] 7. For Kotlin, I suggest we just force people into AGP 7.0/Gradle 7/Java 11 and treat that as our minVersion.

### CODE REVIEW

**Comment by cmelchior** [comment]
Upgrading might be problematic due to https://issuetracker.google.com/issues/187134648. I have not yet been able to determine if there is a work-around.

**Review by q464pp — COMMENTED** [review]
我看不懂英文

**Review by q464pp — COMMENTED** [review]
可以拉取合併嗎？謝謝

**Comment by q464pp** [comment]
JVM SDK可以拉取合併不知道會變什麼樣子?

**Comment by cmelchior** [comment]
Currently blocked on https://issuetracker.google.com/issues/202985154

**Comment by q464pp** [comment]
可以拉取合併了!謝謝

**Comment by cmelchior** [comment]
Finally, ready for review. I disabled us building for Java 8 for now, as fixing that will grow this PR even more, and it is already kinda too big.

Note. Must changes to the realm-transformer was introduced and reviewed already in https://github.com/realm/realm-java/pull/7566

**Review by clementetb — CHANGES_REQUESTED** [review]
LGTM, except that AS fails to build on task: `:realm-library:buildCMakeRelWithDebInfo[x86_64][realm-jni]`.

The build mode `RelWithDebInfo` messes CMakeLists include directory path.

AS 2021.1.1 is required to open the project.

**Review by clementetb — APPROVED** [review]
Great! 🚀

**Pull request merged**
