### PR TITLE
Always update the Version file for the annotation processor

### PR DESCRIPTION
**Pull request by emanuelez**
@cmelchior @kneth @bmunkholm

### CODE REVIEW

**Comment by emanuelez** [comment]
Fixes #926

**Comment by cmelchior** [comment]
Changelog missing, apart from that :+1:

**Comment by emanuelez** [comment]
Changelog:
 * Fixed an issue with the version checker

**Comment by kneth** [comment]
:+1:

**Comment by bmunkholm** [comment]
+1

**Pull request merged**
