### PR TITLE
Added notice about executeTransactionAsync

### PR DESCRIPTION
**Pull request by cmelchior**
We forgot to update the changelog when https://github.com/realm/realm-java/pull/2152/files was merged.

@realm/java

### CODE REVIEW

**Comment by beeender** [comment]
:+1:  Also the java doc needs to be updated.

**Comment by cmelchior** [comment]
Actually `executeTransaction(Transaction, Callback)` is correctly marked deprecated, or did you mean something else?

**Comment by beeender** [comment]
This https://realm.io/docs/java/latest/#asynchronous-transactions

**Comment by cmelchior** [comment]
Yes, good point. I'll add it as part of the release blog post.

**Comment by zaki50** [comment]
:+1:

**Pull request merged**
