### PR TITLE
Missing realm check in some functions

### PR DESCRIPTION
**Pull request by beeender**
* Generate realm check for getter and setter of RealmObject and RealmList.
* Add realm check in RealmObject.removeFromRealm
* Add realm check in RealmResults's remove, removeLast, clear methods
* Add test cases
* Minor warning fix

Maybe related with #1554 ?

### CODE REVIEW

**Comment by beeender** [comment]
retest this please

**Comment by beeender** [comment]
@realm/java

**Comment by kneth** [comment]
What is the performance penalty for these checks?

**Comment by beeender** [comment]
`checkIfValid` is relatively fast, most time consuming part is the `Thread.currentThread()` in there which leads to a jni call into bionic.

For now, since we are checking everywhere to make sure user won't use them in different thread, there is no reason to not check them in those places.

For the future, checking the thread in the jni code or even in the core would be a good idea. That could reduce the jni calls to accelerate a lot.

**Comment by zaki50** [comment]
@beeender Also `RealmResults.size()` should have this check.

**Comment by nhachicha** [comment]
this is off topic but we may consider in the future to expose the checking or not as a RealmConfiguration parameter. Of course we're not a this level of optimisations but it's worth considering post 1.0

**Comment by zaki50** [comment]
Hmm.. calling `Realm.checkIfValid()` in `RealmResults.size()` is overkill?

**Comment by nhachicha** [comment]
@beeender `Realm.clear` should also check IMO I add a comment on the respective Dynamic API call as well

**Comment by beeender** [comment]
@zaki50 I think calling `Realm.checkIfValid()` in `RealmResults.size()` is a bit overkill... User cannot really do anything with a returned size.

**Comment by beeender** [comment]
@realm/java Added check in `Realm.clear()`

**Comment by cmelchior** [comment]
I think we are missing `checkIfValid` from `createObject` as well?

**Comment by cmelchior** [comment]
Added some more thread checks + unit tests. 

Ready for review @realm/java

**Comment by dalinaum** [comment]
LGTM for 390345f :+1:

**Comment by beeender** [comment]
:+1:

**Comment by zaki50** [comment]
:+1:

**Pull request merged**
