### PR TITLE
Add support for ARM64

### PR DESCRIPTION
**Pull request by emanuelez**

### CODE REVIEW

**Comment by emanuelez** [comment]
@kneth @cmelchior @kspangsege

**Comment by emanuelez** [comment]
Fixes #705

**Comment by cmelchior** [comment]
If we are sure that all pointers have been changed to support 64 bit :+1:

**Comment by kneth** [comment]
We are storing native pointers as a `long`. According to http://stackoverflow.com/questions/337268/what-is-the-correct-way-to-store-a-native-pointer-inside-a-java-object this is 64 bit safe.

**Comment by cmelchior** [comment]
I was more referring to the use of the ```PRId64``` syntax, but I wasn't very precise on that :)

**Comment by kneth** [comment]
The `PRId64` selects the appropriate format string for `int64_t` as we cast native pointers to that type  (using the `S64` macro) when logging.

**Pull request merged**
