### PR TITLE
Misleading migration example

### PR DESCRIPTION
**Pull request by mrexmelle**
The PR is created as a solution to issue #3327 Misleading migration example.

### CODE REVIEW

**Comment by Zhuinden** [comment]
I can guarantee that you'll run into checkstyle issues because of the lack of whitespace

**Comment by cmelchior** [comment]
I commented on the issue. While this change is technically correct I think it is trying to cover a case that shouldn't happen for 99% of developers, so I am not sure it is a good idea to merge this. But lets take the discussion in #3327

**Comment by cmelchior** [comment]
Hi @mrexmelle 
Following the discussion in #3327, we will adopt the pattern described there instead. This will also solve the issues you ran into. 

This unfortunately means we won't merge this PR, but thanks for kicking off the discussion.

**Comment by mrexmelle** [comment]
I'm cool. Thanks!

**Pull request closed without merging**
