### PR TITLE
add @deprecated javadoc in RealmQuery.java

### PR DESCRIPTION
**Pull request by mgohin**
Javadoc @deprecated is missing on new deprecated methods in RealmQuery.java

Better to help users

### CODE REVIEW

**Comment by mgohin** [comment]
Done ;)

**Comment by cmelchior** [comment]
Sorry, I meant rebase it against releases as well :) `releases` is the branch where we make patch releases from so merging the changelog and version update in there isn't ideal.

**Comment by mgohin** [comment]
Of course, will do it in a few minutes

**Comment by mgohin** [comment]
Just rebases my `master` branch to `releases` but not sure how to change it in the PR

**Comment by cmelchior** [comment]
I think you can just push it, since the target is already changed on the Github website. If not, feel free to make another PR

**Comment by mgohin** [comment]
Ok, so it's done on my side, you can check it : https://github.com/mgohin/realm-java/tree/releases

**Comment by cmelchior** [comment]
It looks fine by the looks of it, although your branch is a little out of date with `origin`

**Comment by mgohin** [comment]
I created the PR 4 hours ago 😂
Is it better now ?

**Comment by mgohin** [comment]
Be sure to check the README, I add conflicts on it but always took your modifications

**Comment by cmelchior** [comment]
@mgohin The CHANGELOG/version.txt are still wrong, but no worries, I'll just fix this post merge. Thanks for doing this 👍

**Comment by mgohin** [comment]
Thanks ;)
Next time I'll do better

**Pull request merged**
