### PR TITLE
Fix lists of embedded objects not being updated correctly

### LINKED ISSUE #7131: Objects with lists of embedded objects append items to the original list instead of replacing them
```

    @Test
    fun copyToRealmOrUpdate_replacesEmbededdList() {
        realm.beginTransaction()
        val parent = EmbeddedTreeParent()
        parent.middleNodeList = RealmList(EmbeddedTreeNode("1"), EmbeddedTreeNode("2"))
        parent._id = "1"
        realm.copyToRealm(parent)
        realm.commitTransaction()

        realm.beginTransaction()
        parent.middleNodeList.add(EmbeddedTreeNode("3"))
        val managedParent = realm.copyToRealmOrUpdate(parent)
        assertEquals(3, managedParent.middleNodeList.size)
        realm.copyToRealmOrUpdate(parent)
        assertEquals(3, managedParent.middleNodeList.size)
        realm.commitTransaction()
    }
```

This does not work correctly for either `copyToRealmOrUpdate` and `insertOrUpdate`

### PR DESCRIPTION
**Pull request by cmelchior**
Closes #7131

It turned out that our autogenerated code did the wrong thing for `RealmList<SomeEmbeddedClass>`. When using `copyToRealmOrUpdate` we didn't clear the original list, so items were appended to the original list instead of replacing it.

For `insertOrUpdate` the error only manifested if the length of the original and new list was the same.

Note. The current implementation for normal objects has specialized logic for lists of similar size because it tries to avoid the problem of the input list being the same as the output list. This specialized use breaks for embedded objects with this fix. I deemed this acceptable because 1) It is a very niche use cache and 2) Supporting it seemed very difficult as we cannot move easily move embedded objects around.

### CODE REVIEW

**Review by rorbech — COMMENTED** [review]
Looks good - Except I am not really sure I read the NOTE right - What exactly would not work?

**Comment by cmelchior** [comment]
If you did something like this:

```
realm.executeTransaction {
        val parent = EmbeddedTreeParent(_id = "1")
        parent.middleNodeList = RealmList(EmbeddedTreeNode("1"), EmbeddedTreeNode("2"))
        val managedParent = it.copyToRealmOrUpdate(parent)
        parent.middleNodeList = managedParent.middleNodeList // Move managed list to unmanaged object

       // Update parent again with the same managed list. This will break because there is no easy to check if it
       // is the same list or if it is a new list with the same elements.
       it.insertOrUpdate(parent)
}
```

**Comment by rorbech** [comment]
> If you did something like this:
> 
> ```
> realm.executeTransaction {
>         val parent = EmbeddedTreeParent(_id = "1")
>         parent.middleNodeList = RealmList(EmbeddedTreeNode("1"), EmbeddedTreeNode("2"))
>         val managedParent = it.copyToRealmOrUpdate(parent)
>         parent.middleNodeList = managedParent.middleNodeList // Move managed list to unmanaged object
> 
>        // Update parent again with the same managed list. This will break because there is no easy to check if it
>        // is the same list or if it is a new list with the same elements.
>        it.insertOrUpdate(parent)
> }
> ```

I wouldn't deem it that _niche_ use casse, so if we go with it we should definitely highlight it somewhere.

**Review by rorbech — APPROVED** [review]
Probably highlight the consequence of the NOTE somewhere.

**Pull request merged**
