### PR TITLE
retrofit-2 documentation

### PR DESCRIPTION
**Pull request by AKiniyalocts**
This is in reference to #1808

### CODE REVIEW

**Comment by beeender** [comment]
Thanks a lot for your help! Our website is maintained on the other github repo which is not public yet... Can I have the honor to move this there?

**Comment by AKiniyalocts** [comment]
Of course!

**Comment by cmelchior** [comment]
Hi @AKiniyalocts 
Thank you very much :+1: . I moved this to our documentation repo and integrated the change. It should be visible in a few minutes.

**Comment by AKiniyalocts** [comment]
@cmelchior happy to help! Thanks for Realm!

**Pull request closed without merging**
