### PR TITLE
Compacting encrypted Realms is working.

### LINKED ISSUE #1033: Enable compacting encrypted Realms
`BaseRealm.compact()` is now using Object store's `compact` to do its magic.

### PR DESCRIPTION
**Pull request by kneth**
Closes #1033

Finally!!!!!

@finnschiermer @realm/java

### CODE REVIEW

**Comment by finnschiermer** [comment]
WootWoot - :+1:

**Comment by EdwardvanRaak** [comment]
Documentation on `Realm.compactRealm` still says it can throw an illegal argument exception.

**Comment by dalinaum** [comment]
@EdwardvanRaak Good catch. It should be updated.

**Comment by dalinaum** [comment]
@EdwardvanRaak #3973 will fix it. Thanks.

**Pull request merged**
