### PR TITLE
Use ReLinker of JCenter instead of including the dependency ourselves.

### LINKED ISSUE #2596: Use ReLinker of JCenter
#### Goal

> @cmelchior:"ReLinker is now on JCenter. We should use that instead of including the dependency ourselves." #2495

#### Expected Results

Use ReLinker of JCenter instead of including the dependency ourselves.

#### Actual Results

Includes the dependency ourselves.

### PR DESCRIPTION
**Pull request by dalinaum**
There was the problem that se Realm were forced to tell users to add the jitpack repo manually, so we have decided to include the dependency ourselves (#2415).

ReLinker is on JCenter now. We can use Relinker of JCenter instead. It will resolve #2596.

### CODE REVIEW

**Comment by cmelchior** [comment]
If CI is happy I am happy :+1:

**Comment by emanuelez** [comment]
We need to modify the gradle plugin as well so that it doesn't add jitpack as a repo

**Comment by dalinaum** [comment]
@emanuelez Was it already deleted? https://github.com/realm/realm-java/pull/2443/files#diff-fbc37097ca151e18a6db623e59ebdba8L52

**Comment by emanuelez** [comment]
true :+1:

**Pull request merged**
