### PR TITLE
Unit test combining sort() and distinct()

### LINKED ISSUE #3503: findAllSorted and distinct
#### Goal

I'm using `Kotlin` and I'm trying to retrieve objects with `findAllSorted` using a `Long` that's a timestamp to sort them, and then filtering with `distinct`.

I've also asked on [Stackoverflow](http://stackoverflow.com/questions/39708623/realm-findallsorted-and-distinct)
#### Expected Results

I expected to get the "newest objects  for each distinct value of the field used by `distinct`
#### Actual Results

I got the oldest ones.
#### Steps & Code to Reproduce

```
override fun getStuff(): MutableList<Stuff> = realm.where(Stuff::class.java)
        .findAllSorted("timeStamp", Sort.DESCENDING)
        .distinct("otherId")

storage.saveStuff(Stuff("a", otherId=1, timeStamp=1))
storage.saveStuff(Stuff("b", otherId=1, timeStamp=2))
storage.saveStuff(Stuff("c", otherId=1, timeStamp=3))
// Other stuff with different otherId

storage.getStuff()[0].name == "c" // false
```
#### Version of Realm and tooling

Realm version(s): 1.2.0 / 1.1.1

Android Studio version: 2.2

Kotlin Version: 1.0.4

### PR DESCRIPTION
**Pull request by kneth**
Fixes #3503

Connects to #3503
Connects to #3411

### CODE REVIEW

**Comment by Zhuinden** [comment]
Any idea what could be causing this?

**Comment by ironage** [comment]
The order of distinct and the order of sort are now two different things. This has to do with the ability to sort or distinct through a chain of linked properties. Looks like we are always passing `ascending=true` [for distinct](https://github.com/realm/realm-java/blob/63d082809b696a5c7f168e39a7b62ed01d2d23ae/realm/realm-library/src/main/cpp/io_realm_internal_TableView.cpp#L107). Maybe we need a way to let users supply the ordering of distinct in the Java binding?

**Comment by cmelchior** [comment]
It sounds like either the Java binding should remember the sort order to provide it to distinct, but more ideally Core would look at the sort order on any restricting views and use that as the default. What do you think @ironage ?

**Comment by kneth** [comment]
@Zhuinden Not yet, but my hypothesis is that `distinct()` resets the sort order of the table view. If we move to Object Store's `Results` class, we will have to apply the order before calling `findAll()`, and thereby preserve the order to any derived `Results`.

**Comment by ironage** [comment]
I think the current implementation is the most flexible, but maybe doesn’t do what users expect. If Java could add a flag for sort on distinct, I could imagine the following:
```
override fun getStuff(): MutableList<Stuff> = realm.where(Stuff::class.java)
        .findAllSorted(“timeStamp", Sort.ASCENDING)
        .distinct("otherId”, Sort.DESCENDING)
```
That example could show a list of items containing only objects with the last unique `otherId` while the overall results are sorted by earliest time. By changing the two Sort flags you could get four different combinations of results.

If you always want the distinct order the same as in the sort order, we could do that core side. This is not currently supported because sort and distinct operate on different properties. But if this is actually what you want then we could implement it (you would lose the flexibility of the current implementation, but if you don't use it anyways that doesn't matter) is this a preferable approach? @cmelchior @kneth @tgoyne

**Comment by cmelchior** [comment]
Hmm, yes good point. I could why sorting order might be interesting  for distinct alone. We could probably always remember the sorting order for the first sort in the binding and just use that as the default value for distinct if none was provided.

**Comment by kneth** [comment]
We should migrate to object store (implementing `RealmResults` using `Results`) and wait for https://github.com/realm/realm-object-store/issues/183

**Comment by Zhuinden** [comment]
Is this still broken? Results integration is complete

**Comment by kneth** [comment]
@Zhuinden We have kept it open since we don't like core's behaviour. Or rather, we need to extend core's behaviour.

**Comment by Zhuinden** [comment]
Realm-Core 3.0.0 will fix this in Realm-Java 4.0.0.

**Comment by cmelchior** [comment]
This is now fixed with the core upgrade to 3.0.0. So we should merge this PR to get the unit test coverage for the behaviour. 

Ready for review @realm/java

**Pull request merged**
