### PR TITLE
Fix #1641

### LINKED ISSUE #1641: Make sure realm is closed for Async UT
as discussed here https://github.com/realm/realm-java/pull/1637#discussion_r42729295 there might be a risk on slow devices not executing the finally block, causing failing UT to not close the Realm

### PR DESCRIPTION
**Pull request by nhachicha**
Fixes #1641

### CODE REVIEW

**Comment by nhachicha** [comment]
@realm/java

**Comment by bmunkholm** [comment]
Could we please use more descriptive titles or add description. Otherwise you have to lookup the issue just to understand what the purpose of this is.

**Comment by cmelchior** [comment]
We have this check:
```
        if (null != threadAssertionError[0]) {
            throw threadAssertionError[0];
        }
```

in a lot of places now. Could make sense to replace with something like:

```
checkBackgroundErrors(threadAssertionError)
```

and create a helper method to check and throw errors if needed. It could be in a separate PR though. This is :+1:

**Comment by beeender** [comment]
:+1:

**Comment by nhachicha** [comment]
@realm/java

**Comment by emanuelez** [comment]
:+1:

**Comment by dalinaum** [comment]
:+1:

**Pull request merged**
