### PR TITLE
Remove an unnecessary directory of .gitignore

### PR DESCRIPTION
**Pull request by dalinaum**
A very small patch. Please review this @realm/java

### CODE REVIEW

**Comment by zaki50** [comment]
:+1:

**Comment by kneth** [comment]
:+1:

**Comment by emanuelez** [comment]
Should we add the new location of the jnilibs folder?

**Comment by dalinaum** [comment]
@emanuelez We already ignored `*.so` files.

https://github.com/realm/realm-java/pull/1747/files#diff-a084b794bc0759e7a6b77810e01874f2R28

**Comment by cmelchior** [comment]
Just ignoring the .so files should also work as far as I know :+1:

**Comment by zaki50** [comment]
:+1:

**Pull request merged**
