### PR TITLE
Adding Realm.compact() for encrypted Realm files

### LINKED ISSUE #1033: Enable compacting encrypted Realms
`BaseRealm.compact()` is now using Object store's `compact` to do its magic.

### PR DESCRIPTION
**Pull request by kneth**
Closes #1033

Recent changes to Realm's storage engine have enabled compacting of encrypted Realm files.

@realm/java

### CODE REVIEW

**Comment by cmelchior** [comment]
retest this please

**Comment by dalinaum** [comment]
:+1:

**Comment by dalinaum** [comment]
retest this please
I just tested this PR on my laptop. There isn't any problems.

**Comment by dalinaum** [comment]
retest this please

**Pull request closed without merging**
