### PR TITLE
Standardize test timeouts

### PR DESCRIPTION
**Pull request by bmeike**
Make sure that all `await()`s have timeouts, and standardize their lengths.

### CODE REVIEW

**Comment by zaki50** [comment]
This PR should target `releases`

**Comment by zaki50** [comment]
And also #4563 should target `releades`.

**Comment by bmeike** [comment]
Re-opening.  This is basis for work I am doing on master.  I would like to have it in master.  I had a look at putting it in release.  That's not going to get it to master, where I need it, though...

**Comment by cmelchior** [comment]
@bmeike Our automatic merge script will merge `releases` into `master`. To minimise merge conflicts all internal changes should ideally target that branch instead. Since that will minimize merge conflicts in future PR's as well.

**Comment by bmeike** [comment]
Abandoning.  PR #4581 is a combination of this PR and #4563 that targets the release branch.

**Pull request closed without merging**
