### PR TITLE
Fix comment in gridViewExample

### PR DESCRIPTION
**Pull request by maciejwitowski**
findFirst() returns RealmObject not a List.

### CODE REVIEW

**Comment by cmelchior** [comment]
Hi @maciejwitowski 
Thanks for fixing this. We require all contributors to have signed our CLA before I can merge this, but apart from that it looks fine: https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#cla

**Comment by maciejwitowski** [comment]
Thanks for the answer @cmelchior !
I've filled out the form and I hope to contribute more :)

**Comment by dalinaum** [comment]
:+1:

**Comment by cmelchior** [comment]
Merged. Thanks @maciejwitowski

**Pull request merged**
