### PR TITLE
Converted RealmResultsTests to JUnit4

### PR DESCRIPTION
**Pull request by cmelchior**
Note some tests seemed out of place. I added TODO's for those so they can be fixed later instead of making noise to this PR.

Also prefixing all tests with the method being tested seemed to catch a couple of redundant tests :smile: 

@realm/java

### CODE REVIEW

**Comment by cmelchior** [comment]
retest this please

**Comment by dalinaum** [comment]
I finally read all modifications. :+1:

**Comment by beeender** [comment]
Stupid github review, doesn't show the diff at all.

> TODO Check if should returns null. Should removeLast work on the empty list?
`TableView.removeLast` is checking `isEmpty()` before removing, so it will work without doing anything. Note here: `TableView.removeLast` can just call core's `TableView.remove_last` directly. But it is something we can change in the object store adaption.

**Comment by kneth** [comment]
:+1:

**Comment by cmelchior** [comment]
retest this please

**Comment by cmelchior** [comment]
retest this please

**Pull request merged**
