### PR TITLE
Unit test for #4140.

### PR DESCRIPTION
**Pull request by bmeike**
This UT tests the scenario described in #4140.  It fails.

### CODE REVIEW

**Comment by bmeike** [comment]
The failing test demonstrates the problem.

**Comment by bmeike** [comment]
Christian points out that this merge is to the wrong branch.  It should be `releases`, not `master`

**Comment by beeender** [comment]
needs fix from core https://github.com/realm/realm-core/pull/2445
Also, after core gets merged & released, some changes needs to be made in the Object Store `realm::set_temporary_directory`.

**Comment by beeender** [comment]
needs https://github.com/realm/realm-object-store/pull/389 to be merged then update Object Store sub-module in this PR.

**Comment by beeender** [comment]
ready for review.

**Pull request merged**
