### PR TITLE
Converted TypedBasedNotificationTests to JUnit4

### PR DESCRIPTION
**Pull request by cmelchior**
@realm/java

### CODE REVIEW

**Comment by beeender** [comment]
https://github.com/realm/realm-java/blob/cm/junit4-typedbased/realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java#L651
No need of `try` block i think? `looperThread.testComplete();` should be called after other 3 looper thread quit. Otherwise it is a risk that test is finished, but the other 3 looper threads are not.

**Comment by beeender** [comment]
Except one comments, :+1:

**Comment by cmelchior** [comment]
Fixed

**Comment by beeender** [comment]
:+1:

**Comment by zaki50** [comment]
:+1:

**Pull request merged**
