### PR TITLE
add conf to build for x86_64

### LINKED ISSUE #1167: Add x86_64 Support
I know there isn't a ton of devices out there that have this arch yet but there are x86_64 emulators available. Is there a timeline for this to be supported?

Thanks!

### PR DESCRIPTION
**Pull request by nhachicha**
Fixes #1167 
Please wait for https://github.com/realm/realm-core/pull/873 before merging this PR as it provides the static library needed by JNI

### CODE REVIEW

**Comment by nhachicha** [comment]
@emanuelez @kneth @cmelchior the core https://github.com/realm/realm-core/pull/861 build is back to normal

**Comment by cmelchior** [comment]
This probably won't build until realm/realm-core#861 has been merged. That said, only thing missing seem to be an update of the ```changelog.txt```

**Comment by kneth** [comment]
:+1:

**Comment by nhachicha** [comment]
Even though realm/realm-core#873 has been merged. This will not build until _core_ rollout  a new version. (we still use `ext.coreVersion = '0.89.2'` in `realm-jni/build.gradle`)

**Comment by cmelchior** [comment]
Does this work with 0.89.5 (current core) or do we need  0.90.x (null)?

**Comment by kneth** [comment]
Version 0.89.5 does not include x86_64 support.

**Comment by cmelchior** [comment]
retest this please

**Comment by cmelchior** [comment]
This should be ready for review as well after the latest core has been merged to master @realm/java

**Comment by cmelchior** [comment]
retest this please

**Comment by cmelchior** [comment]
With latest core merged to master, this should be ready for review: @realm/java

**Comment by kneth** [comment]
Can we upgrade to gcc 4.9 for other architectures?

**Comment by cmelchior** [comment]
We can upgrade, but should be done in a separate PR as it might affect other things as well.

**Comment by kneth** [comment]
:+1:

**Comment by beeender** [comment]
:+1:

**Comment by beeender** [comment]
retest this please

**Pull request merged**
