### PR TITLE
Merge remote-tracking branch 'origin/releases' into mc/merge/0.89_f1f99a91

### PR DESCRIPTION
**Pull request by beeender**
Add bullet to changelog about behavior change of RealmList.first() and RealmList.last()

#2680

### CODE REVIEW

**Comment by zaki50** [comment]
@realm/java

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
CI:retest this

**Comment by zaki50** [comment]
retest this please

**Comment by zaki50** [comment]
retest this please

**Comment by beeender** [comment]
:+1:

**Pull request merged**
