### PR TITLE
Method/class cleanup

### PR DESCRIPTION
**Pull request by cmelchior**
Preparing to split Realm into Realm/DynamicRealm.

This PR removes all deprecated methods from Realm + deletes an unused class (that was commented out)
+ Fixed all unit tests.

@realm/java

### CODE REVIEW

**Comment by beeender** [comment]
:+1: javadoc failed to build :(

**Comment by cmelchior** [comment]
Don't make pull requests later friday. Ready for review

@realm/java

**Comment by emanuelez** [comment]
Nice! :+1:

**Comment by cmelchior** [comment]
Bump @realm/java

**Comment by beeender** [comment]
:+1:

**Comment by cmelchior** [comment]
retest this please

**Pull request merged**
