### PR TITLE
Fix too many open files crash

### LINKED ISSUE #4002: could not create WeakRealmNotifier ALooper message pipe: Too many open files
From https://github.com/realm/realm-object-store/issues/319 (see attached files there)

hello,
I try to evaluate different databases inside one android app- Therefore I created different scenarios. The scenarios are different in the size and count of objects I will store.

All calls to the realm database came from a class I called "RealmDataManager". Inside this I implement differend methods which I need for my evaluation.

I use a IntentService which gets started from my Mainactivity. Inside my IntentService I defined the different scenarios and what to do for each.

At the Moment I have one problem. After my 4th Szenario (from 90 szenario's) I got the following Output in Logcat,

01-06 13:51:54.957 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.959 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.963 14995-15012/de.gerding.dbcompare E/Parcel: dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Too many open files
01-06 13:51:54.966 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.967 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.972 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.974 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.980 14995-15012/de.gerding.dbcompare E/Parcel: dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Too many open files
01-06 13:51:54.982 14995-15012/de.gerding.dbcompare E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
01-06 13:51:54.982 14995-15012/de.gerding.dbcompare I/Adreno: QueueBuffer: queueBuffer failed
01-06 13:51:54.982 14995-15012/de.gerding.dbcompare W/OpenGLRenderer: swapBuffers encountered EGL_BAD_SURFACE on 0x7f82d04940, halting rendering...
01-06 13:51:54.984 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.985 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:55.014 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:55.016 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
...

Can you help me to figure out what I should change to solve this?

It's not a big problem, it looks like it works although this logcat output gets spammed. But I am not sure if it works for a long time. In my mainactivity I show an ProgressDialog when I start my "MessService", and this ProgressDialog in style circle doesn't move anymore when I got the logcat spam.

I will attach you some of my classes.
RealmDataManager - where all calls to the database are implemented.

MessService - where all scenarios are defined and you can see how I use the RealmDataManager
I take some comments inside my MessService so that not alle scenarios are used at the moment because some scenarios needs long time and this is not fine for debugging.

RealmCANDaten - one of my two objecttypes stored in the database

RealmFahrt - the other objecttype stored in the database

If you need more information for reproducing please let me know that. I hope we can fix this issue together.

### PR DESCRIPTION
**Pull request by beeender**
Update object store to bd3825e949 to fix #4002

### CODE REVIEW

**Comment by Miger88** [comment]
How can I update to bd3825e949?
How can I implement the new solution?

**Comment by Miger88** [comment]
Does that mean I have to use realm 2.2.2?

**Comment by Zhuinden** [comment]
It will be part of the snapshot once this is merged.

**Comment by Miger88** [comment]
How can I use this snapshot version?

**Comment by Miger88** [comment]
Thanks. I will try this. Is version 2.3.0-SNAPSHOT the right version?

**Comment by beeender** [comment]
@Miger88 you have to wait a few hours later after it gets merged.

**Comment by Miger88** [comment]
okay thanks

**Comment by JamesMcIntosh** [comment]
Is anyone fixing the conflict in CHANGELOG.md so this can be merged?

**Comment by Miger88** [comment]
If I see right the new version is merged now. What name has the snapshot that I can use? In theversions.txt it is still 2.3.0-Snapshot

**Comment by beeender** [comment]
@Miger88 The snapshot release is built from our master branch. So the version will be changed if there is a new minor version released from the master branch.

**Comment by Miger88** [comment]
So at the moment I cannot test the new snapshot?

**Comment by beeender** [comment]
@Miger88 anything merged to the `releases` branch will be automatically merged to the `master` branch. So this fix is on master as well. You can use the snapshot to test it. 

See https://github.com/realm/realm-java#using-snapshots

Don't forget to clean & rebuild your project.

**Comment by Miger88** [comment]
thank you very much for this great support. I tried it with 2.3.0-SNAPSHOT again and now I didn't get the log Messages. Problem is solved.

**Pull request merged**
