### PR TITLE
Added a support for androidTest on API 9 devices

### PR DESCRIPTION
**Pull request by zaki50**
This enables for us to reproduce #3804 on our unit test.

@realm/java 

After applying this change, our android test reproduces #3804 on ARM with API 9 device, and #3735 on x86  with API 9 emulator.

### CODE REVIEW

**Comment by kneth** [comment]
@zaki50 Since you only modify, is it correct to assume this change has no impact on the final product?

**Comment by zaki50** [comment]
@kneth yes. I'm sure this change has no impact for the product.

`realm/realm-library/src/main/AndroidManifest.xml` is the only file which has a change related to product, but it's just a simplification.
Should I revert that?

**Comment by kneth** [comment]
@zaki50 Sounds great. No reason to revert.

**Comment by zaki50** [comment]
@kneth I updated `realm/realm-library/build.gradle` to minimize the modification.

**Pull request merged**
