### PR TITLE
Upgrade example to GSON 2.5

### PR DESCRIPTION
**Pull request by cmelchior**
Testing #1821 

Workaround is still required.

@realm/java

### CODE REVIEW

**Comment by kneth** [comment]
Wow, what a change :+1:

**Comment by Gryzor** [comment]
You'll probably want to update this: https://realm.io/docs/java/latest/#gson

**Comment by cmelchior** [comment]
Yes, we should update the website as well

**Comment by beeender** [comment]
Most elegant and nattiest change i have ever met! Best programmer in the world! :+1:

**Pull request merged**
