### PR TITLE
Updated changelog for latest contributions

### PR DESCRIPTION
**Pull request by edualonso**
Added changelog entries for latest contributions from the community:
https://github.com/realm/realm-java/pull/7639
https://github.com/realm/realm-java/pull/7646
https://github.com/realm/realm-java/pull/7648

### CODE REVIEW

**Comment by edualonso** [comment]
@cla-bot check

**Comment by blagoev** [comment]
@cla-bot check

**Comment by blagoev** [comment]
@cla-bot check

**Comment by edualonso** [comment]
Opening new PR to avoid issues with the CLA bot.

**Pull request closed without merging**
