### PR TITLE
Fixed DynamicRealmObject.getObject()/setObject() using the wrong table

### LINKED ISSUE #1451: DynamicRealmObject setObject() does not check types properly
In `DynamicRealmObject`'s `setObject(String fieldName, DynamicRealmObject value)`, the type of the parameter should be compared against the field's defined type. Instead, it is being compared against the type of the object itself.

The offending lines are in DynamicRealmObject.java lines 404-409.

### LINKED ISSUE #1912: setObject and getObject not working as expected in Migration
In my migration I create a new field (which has the same field as an old field, therefore with the "_tmp" field) and I want to put in set on the new object a field that was before on the old object.

I think some example code is clearer:

``` 
schema.get("Test")
    .addRealmObjectField("field_tmp", newSchema)
    .transform(new RealmObjectSchema.Function() {
        @Override
        public void apply(DynamicRealmObject object) {
            DynamicRealmObject newInstance = realm.createObject("NewObject");
            newInstance.setObject("user", object.getObject("user"));
            object.setObject("field_tmp", newInstance);
        }
    })
    .removeField("user")
    .removeField("field")
    .renameField("field_tmp", "field");
```

When I try to execute that in my migration I get the following error:
```
java.lang.IllegalArgumentException: Type of object is wrong. Was class_Test, expected class_NewObject
```

Can you help me with that?

### PR DESCRIPTION
**Pull request by cmelchior**
Fixes #1912 
Fixes #1451 

@realm/java

### CODE REVIEW

**Comment by cmelchior** [comment]
Retest this please

**Comment by kneth** [comment]
The devil hides in the details :-)

:+1:

**Comment by zaki50** [comment]
:+1:

**Comment by cmelchior** [comment]
retest this please

**Pull request merged**
