### PR TITLE
Fix transformer in lib project on Windows

### LINKED ISSUE #2484: build execution fails on Windows after update to 88.2
#### Goal
Build the app successfully after update to 88.2

#### Expected Results
I am able to build

#### Actual Results
Error:Execution failed for task ':app:transformClassesWithRealmTransformerForStagingDebug'.
cannot find io/realm/MyClassRealmProxy: io.realm.MyClassRealmProxy found in io/realm/MyClassRealmProxy.class

#### Steps & Code to Reproduce
I am seeing this error after update to 88.2. When I downgrade back to 87.2 the project builds OK.

#### Version of Realm and tooling
Realm version(s): 87.2, 88.2

Android Studio version: 1.5.1
OS Version: Windows 10

### PR DESCRIPTION
**Pull request by beeender**
The separator in jar file might not be File.separatorChar
Fix #2484

### CODE REVIEW

**Comment by cmelchior** [comment]
Nice :+1:

**Comment by CarlosMChica** [comment]
any ETA for when this is going to be released?

**Comment by cmelchior** [comment]
Hi @CarlosMChica There will be a 0.88.3 release early next week.

**Comment by CarlosMChica** [comment]
@cmelchior that's good news. 

Thanks a lot for taking care of it in such a short notice :+1:

**Comment by beeender** [comment]
retest this please

**Comment by CarlosMChica** [comment]
@beeender will do it first thing tomorrow morning. I just looked for the new version but couldn't find it. Guess it's 0.88.3?

**Comment by emanuelez** [comment]
@CarlosMChica the comment from @beeender was to trigger an automatic build on our CI system so it was not directed to you, but I understand the confusion. Maybe we should change the trigger phrase. :)

**Comment by CarlosMChica** [comment]
@emanuelez that's ok hehe, but yeah you may want to change it to avoid confusion :). However, Will be possible to have the new version tomorrow?

**Comment by cmelchior** [comment]
Hi @CarlosMChica Our CI is misbehaving currently, but once we get that fixed we will release.

**Comment by CarlosMChica** [comment]
@cmelchior thanks

**Comment by cmelchior** [comment]
retest this please

**Pull request merged**
